## PyLiPD OOP Demo

#### PyLiPD Ontologies

The PyLiPD OOP Classes are generated from the ontologies at: https://linked.earth/ontology/
* The [Linked Earth Core Ontology](https://linked.earth/ontology/core/2.0.0/index-en.html) provides the main concepts and relationships to describe a paleoclimate dataset and its values.
* The [Archive Type Ontology](https://linked.earth/ontology/archive/2.0.0/index-en.html) describes a taxonomy of the most common types of archives.
* The [Paleo Variables Ontology](https://linked.earth/ontology/paleo_variables/2.0.0/index-en.html) describes a taxonomy of the most common types of paleo variables.
* The [Paleo Proxy Ontology](https://linked.earth/ontology/paleo_proxy/2.0.0/index-en.html) describes a taxonomy of the most common types of paleo proxies.
* The [Paleo Units Ontology](https://linked.earth/ontology/paleo_units/2.0.0/index-en.html) describes a taxonomy of the most common types of paleo units.
* The [Interpretation Ontology](https://linked.earth/ontology/interpretation/2.0.0/index-en.html) describes a taxonomy of the most common interpretations.
* The [Instrument Ontology](https://linked.earth/ontology/instrument/2.0.0/index-en.html) describes a taxonomy of the most common instrument for taking measurements.
* The [Chron Variables Ontology](https://linked.earth/ontology/chron_variables/2.0.0/index-en.html) describes a taxonomy of the most common types of chron variables.
* The [Chron Proxy Ontology](https://linked.earth/ontology/chron_proxy/2.0.0/index-en.html) describes a taxonomy of the most common types of chron proxies.
* The [Chron Units Ontology](https://linked.earth/ontology/chron_units/2.0.0/index-en.html) describes a taxonomy of the most common types of chron units.

### PyLiPD OOP Classes UML Diagram
![PyLiPD OOP Classes UML Diagram](UMLDiagram.png "yLiPD OOP Classes UML Diagram")

## Reading an existing LiPD file

In [23]:
# Dataset is the Main OOP Class
from pylipd.classes.dataset import Dataset

# LiPD is the LiPD parser/writer
from pylipd.lipd import LiPD

# Load LiPD files as usual.
# - This loads the LiPD data into the internal RDF graph
path = '../data/Pages2k'
D = LiPD()
D.load_from_dir(path)

# Convert the LiPD datasets to the PyLiPD OOP "Dataset" class. 
# - This allows to modify the datasets via OOP calls in memory
# - To write the LiPD back, we have to call the save function
datasets = D.get_datasets()

for ds in datasets:
    # Now we can call individual function on the dataset to get its details
    print("\n")
    print(ds.getName())
    print("=========================")
    for funding in ds.getFundings():
        if funding.getGrants():
            print(f"Funding: {funding.getGrants()}")
    
    for pub in ds.getPublications():
        print(f"Publication: {pub.getTitle()} by {list(map(lambda x: x.getName(), pub.getAuthors()))}")

    for pd in ds.getPaleoData():
        for table in pd.getMeasurementTables():
            print(f"- Paleo Table: {table.getFileName()}")
            
            # Can get the dataframe for the whole table
            df = table.getDataFrame(use_standard_names=True)
            display(df.head())

            # The returned dataframe also contains the attributes for the variables
            for varname in df.attrs:
                vardata = df.attrs[varname]
                print(varname, vardata)

            # Can also get the variables one by one and make calls to their class functions
            print(f"Missing Value: {table.getMissingValue()}")
            for var in table.getVariables():
                if var.getUnits():
                    print(f"- {var.getName()} [{var.getUnits().getLabel()}]")
                else:
                    print(f"- {var.getName()}")

Loading 16 LiPD files

100%|██████████| 16/16 [00:00<00:00, 59.56it/s]

Loaded..


Ocn-RedSea.Felis.2000
=========================
Publication: Tropical sea surface temperatures for the past four centuries reconstructed from coral archives by ['Henry C. Wu', 'Jens Zinke', 'Michael N. Evans', 'Casey P. Saenger', 'Jessica E. Tierney', 'Kevin J. Anchukaitis', 'Cyril Giry', 'K. Halimeda Kilbourne', 'Nerilie J. Abram']
Publication: A coral oxygen isotope record from the northern Red Sea documenting NAO, ENSO, and North Pacific teleconnections on Middle East climate variability since the year 1750 by ['Yossi Loya', 'Ahmed H. Nawar', 'Maoz Fine', 'Gerold Wefer', 'Jürgen Pätzold', 'Thomas Felis']
Publication: World Data Center for Paleoclimatology by ['T. Felis']
- Paleo Table: Ocn-RedSea.Felis.2000.paleo1measurement1.csv

   d18O      year
0 -4.12  1995.583
1 -3.82  1995.417
2 -3.05  1995.250
3 -3.02  1995.083
4 -3.62  1994.917

d18O {'@id': 'http://linked.earth/lipd/Ocn-RedSea.Felis.2000.paleo1measurement1.Ocean2kHR_019.d18O', 'interpretation': [{'@id': 'http://linked.earth/lipd/Ocn-RedSea.Felis.2000.paleo1measurement1.Ocean2kHR_019.d18O.Interpretation1', 'direction': 'negative', 'scope': 'climate', 'seasonality': 'subannual', 'variable': 'temperature', 'variableDetail': 'sea@surface'}], 'archiveType': 'Coral', 'number': 1, 'hasMaxValue': -2.48, 'hasMeanValue': -3.4047, 'hasMedianValue': -3.42, 'hasMinValue': -4.19, 'variableName': 'd18O', 'notes': '; climateInterpretation_seasonality changed - was originally bimonthly', 'inCompilationBeta': {'@id': 'http://linked.earth/lipd/Pages2kTemperature.66deb385100fc', 'compilationName': 'Pages2kTemperature', 'compilationVersion': '2_1_1'}, 'proxy': 'd18O', 'resolution': {'@id': 'http://linked.earth/lipd/Ocn-RedSea.Felis.2000.paleo1measurement1.Ocean2kHR_019.d18O.Resolution', 'hasMaxValue': 0.167, 'hasMeanValue': 0.1667, 'hasMedianValue': 0.167, 'hasMinValue': 0.166, 'units': 'yr AD'}, 'hasStandardVariable': 'd18O', 'units': 'permil', 'TSid': 'Ocean2kHR_019', 'variableType': 'measured', 'measurementTableMD5': 'f01d2261b925e04c2a4ef14e505ee173', 'paleoDataTableName': 'measTable', 'pages2kID': 'Ocn_080', 'proxyObservationType': 'd18O', 'iso2kUI': 'CO00FERA01A', 'measurementTableName': 'measurementTable1', 'sensorGenus': 'Porites', 'sensorSpecies': 'NA', 'qCCertification': 'JZ, NJA', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Ocn-RedSea.Felis.2000.txt', 'useInGlobalTemperatureAnalysis': True, 'ocean2kID': 'IndianRedSeaFelis2000'}
year {'@id': 'http://linked.earth/lipd/Ocn-RedSea.Felis.2000.paleo1measurement1.PYTXPC7HUA2.year', 'archiveType': 'Coral', 'number': 2, 'description': 'Year AD', 'hasMaxValue': 1995.583, 'hasMeanValue': 1873.3333, 'hasMedianValue': 1873.3335, 'hasMinValue': 1751.083, 'variableName': 'year', 'resolution': {'@id': 'http://linked.earth/lipd/Ocn-RedSea.Felis.2000.paleo1measurement1.PYTXPC7HUA2.year.Resolution', 'hasMaxValue': 0.167, 'hasMeanValue': 0.1667, 'hasMedianValue': 0.167, 'hasMinValue': 0.166, 'units': 'yr AD'}, 'hasStandardVariable': 'year', 'units': 'yr AD', 'TSid': 'PYTXPC7HUA2', 'variableType': 'inferred', 'measurementTableMD5': 'f01d2261b925e04c2a4ef14e505ee173', 'measurementTableName': 'measurementTable1', 'paleoDataTableName': 'measTable', 'dataType': 'float', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Ocn-RedSea.Felis.2000.txt', 'inferredVariableType': 'Year'}
Missing Value: NaN
- d18O [permil]
- year [yr AD]


Ant-WAIS-Divide.Severinghaus.2012
=========================
Publication: This study by ['Severinghaus J.']
Publication: Little Ice Age cold interval in West Antarctica: Evidence from borehole temperature at the West Antarctic Ice Sheet (WAIS) Divide by ['Bruce D. Cornuelle', 'Jeffrey P. Severinghaus', 'Anais J. Orsi']
- Paleo Table: Ant-WAIS-Divide.Severinghaus.2012.paleo1measurement1.csv

   temperature  year  uncertainty
0      -29.607     8        1.327
1      -29.607     9        1.328
2      -29.606    10        1.328
3      -29.606    11        1.329
4      -29.605    12        1.330

temperature {'@id': 'http://linked.earth/lipd/Ant-WAIS-Divide.Severinghaus.2012.paleo1measurement1.LPDb9285123.temperature', 'interpretation': [{'@id': 'http://linked.earth/lipd/Ant-WAIS-Divide.Severinghaus.2012.paleo1measurement1.LPDb9285123.temperature.Interpretation1', 'basis': 'physics', 'direction': 'positive', 'scope': 'climate', 'seasonality': 'Annual', 'variable': 'temperature', 'variableDetail': 'ice@surface'}], 'archiveType': 'Borehole', 'number': 1, 'description': 'surface temperature', 'hasMaxValue': -28.472, 'hasMeanValue': -29.8457, 'hasMedianValue': -29.7745, 'hasMinValue': -30.423, 'variableName': 'temperature', 'notes': '; paleoData_units changed - was originally deg C; climateInterpretation_seasonality changed - was originally annual', 'inCompilationBeta': {'@id': 'http://linked.earth/lipd/Pages2kTemperature.66deb38514785', 'compilationName': 'Pages2kTemperature', 'compilationVersion': '2_1_1'}, 'proxy': 'borehole', 'resolution': {'@id': 'http://linked.earth/lipd/Ant-WAIS-Divide.Severinghaus.2012.paleo1measurement1.LPDb9285123.temperature.Resolution', 'hasMaxValue': 1.0, 'hasMeanValue': 1.0, 'hasMedianValue': 1.0, 'hasMinValue': 1.0, 'units': 'yr AD'}, 'hasStandardVariable': 'temperature', 'units': 'degC', 'TSid': 'LPDb9285123', 'variableType': 'inferred', 'pages2kID': 'Ant_027', 'measurementTableName': 'measurementTable1', 'paleoDataTableName': 's1', 'dataType': 'float', 'qCCertification': 'AJO', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Ant-WAIS-Divide.Severinghaus.2012.txt', 'measurementTableMD5': 'a50953ab380f2ae67a894418f6e817fd', 'inferredVariableType': 'Temperature', 'measurementMethod': 'inverse model', 'useInGlobalTemperatureAnalysis': True}
year {'@id': 'http://linked.earth/lipd/Ant-WAIS-Divide.Severinghaus.2012.paleo1measurement1.PYTAAFWZCUK.year', 'archiveType': 'Borehole', 'number': 2, 'description': 'Year AD', 'hasMaxValue': 2007.0, 'hasMeanValue': 1007.5, 'hasMedianValue': 1007.5, 'hasMinValue': 8.0, 'variableName': 'year', 'resolution': {'@id': 'http://linked.earth/lipd/Ant-WAIS-Divide.Severinghaus.2012.paleo1measurement1.PYTAAFWZCUK.year.Resolution', 'hasMaxValue': 1.0, 'hasMeanValue': 1.0, 'hasMedianValue': 1.0, 'hasMinValue': 1.0, 'units': 'yr AD'}, 'hasStandardVariable': 'year', 'units': 'yr AD', 'TSid': 'PYTAAFWZCUK', 'variableType': 'inferred', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Ant-WAIS-Divide.Severinghaus.2012.txt', 'inferredVariableType': 'Year', 'paleoDataTableName': 's1', 'dataType': 'float', 'measurementTableMD5': 'a50953ab380f2ae67a894418f6e817fd', 'measurementTableName': 'measurementTable1'}
uncertainty {'@id': 'http://linked.earth/lipd/Ant-WAIS-Divide.Severinghaus.2012.paleo1measurement1.LPDa7a4074f.uncertainty_temperature', 'interpretation': [{'@id': 'http://linked.earth/lipd/Ant-WAIS-Divide.Severinghaus.2012.paleo1measurement1.LPDa7a4074f.uncertainty_temperature.Interpretation1', 'scope': 'climate'}], 'archiveType': 'Borehole', 'number': 3, 'description': 'temperature uncertainty', 'hasMaxValue': 1.332, 'hasMeanValue': 1.0858, 'hasMedianValue': 1.153, 'hasMinValue': 0.023, 'variableName': 'uncertainty_temperature', 'notes': 'Not a temperature proxy', 'inCompilationBeta': {'@id': 'http://linked.earth/lipd/Pages2kTemperature.66deb38514a5e', 'compilationName': 'Pages2kTemperature', 'compilationVersion': '2_1_1'}, 'resolution': {'@id': 'http://linked.earth/lipd/Ant-WAIS-Divide.Severinghaus.2012.paleo1measurement1.LPDa7a4074f.uncertainty_temperature.Resolution', 'hasMaxValue': 1.0, 'hasMeanValue': 1.0, 'hasMedianValue': 1.0, 'hasMinValue': 1.0, 'units': 'yr AD'}, 'hasStandardVariable': 'uncertainty', 'units': 'degC', 'TSid': 'LPDa7a4074f', 'variableType': 'inferred', 'paleoDataTableName': 's1', 'dataType': 'float', 'measurementTableMD5': 'a50953ab380f2ae67a894418f6e817fd', 'measurementMethod': 'inverse model', 'useInGlobalTemperatureAnalysis': False, 'qCCertification': 'MAC', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Ant-WAIS-Divide.Severinghaus.2012.txt', 'measurementTableName': 'measurementTable1'}
Missing Value: NaN
- temperature [degC]
- year [yr AD]
- uncertainty_temperature [degC]


Asi-SourthAndMiddleUrals.Demezhko.2007
=========================
Publication: Climatic changes in the Urals over the past millennium; an analysis of geothermal and meteorological data by ['D. Yu. Demezhko', 'I. V. Golovanova']
Publication: This study by ['D Demezhko']
- Paleo Table: Asi-SourthAndMiddleUrals.Demezhko.2007.paleo1measurement1.csv

   year  temperature
0   800        0.166
1   850        0.264
2   900        0.354
3   950        0.447
4  1000        0.538

year {'@id': 'http://linked.earth/lipd/Asi-SourthAndMiddleUrals.Demezhko.2007.paleo1measurement1.PYTX5TD5SOT.year', 'archiveType': 'Borehole', 'number': 2, 'description': 'Year AD', 'hasMaxValue': 1950.0, 'hasMeanValue': 1375.0, 'hasMedianValue': 1375.0, 'hasMinValue': 800.0, 'variableName': 'year', 'resolution': {'@id': 'http://linked.earth/lipd/Asi-SourthAndMiddleUrals.Demezhko.2007.paleo1measurement1.PYTX5TD5SOT.year.Resolution', 'hasMaxValue': 50.0, 'hasMeanValue': 50.0, 'hasMedianValue': 50.0, 'hasMinValue': 50.0, 'units': 'yr AD'}, 'hasStandardVariable': 'year', 'units': 'yr AD', 'TSid': 'PYTX5TD5SOT', 'variableType': 'inferred', 'measurementTableName': 'measurementTable1', 'inferredVariableType': 'Year', 'dataType': 'float', 'paleoDataTableName': 'Data', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Asi-SourthAndMiddleUrals.Demezhko.2007.txt', 'measurementTableMD5': '702a1f56e561a429ca605b890aefd69c'}
temperature {'@id': 'http://linked.earth/lipd/Asi-SourthAndMiddleUrals.Demezhko.2007.paleo1measurement1.Asia_230.temperature', 'interpretation': [{'@id': 'http://linked.earth/lipd/Asi-SourthAndMiddleUrals.Demezhko.2007.paleo1measurement1.Asia_230.temperature.Interpretation1', 'basis': 'N/A', 'direction': 'positive', 'scope': 'climate', 'seasonality': 'Annual', 'variable': 'temperature', 'variableDetail': 'ground@surface'}], 'archiveType': 'Borehole', 'number': 1, 'description': 'inferred ground surface temperature (GST) anomaly', 'hasMaxValue': 0.724, 'hasMedianValue': 0.215, 'hasMinValue': -1.224, 'variableName': 'temperature', 'notes': 'Half-centennial resolution. Elevation estimated from GoogleEarth; rounded to 100 m', 'inCompilationBeta': {'@id': 'http://linked.earth/lipd/Pages2kTemperature.66deb385180ca', 'compilationName': 'Pages2kTemperature', 'compilationVersion': '2_1_1'}, 'proxy': 'borehole', 'resolution': {'@id': 'http://linked.earth/lipd/Asi-SourthAndMiddleUrals.Demezhko.2007.paleo1measurement1.Asia_230.temperature.Resolution', 'hasMaxValue': 50.0, 'hasMeanValue': 50.0, 'hasMedianValue': 50.0, 'hasMinValue': 50.0, 'units': 'yr AD'}, 'hasStandardVariable': 'temperature', 'uncertainty': 'Asi-SourthAndMiddleUrals.Demezhko.2007.paleo1measurement1.Asia_230.temperature.Uncertainty', 'units': 'degC', 'TSid': 'Asia_230', 'variableType': 'inferred', 'measurementTableName': 'measurementTable1', 'detail': 'GST anomaly relative to (800-1950) mean', 'paleoDataTableName': 'Data', 'dataType': 'float', 'measurementMaterial': 'N/A', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Asi-SourthAndMiddleUrals.Demezhko.2007.txt', 'measurementTableMD5': '702a1f56e561a429ca605b890aefd69c', 'qCCertification': 'AAG', 'pages2kID': 'Asi_244', 'measurementMethod': 'borehole temperature inversion (see Demezhko, D. Y., Shchapov, V. A., Glob. Planet. Change, 29, 219–230, 2001)', 'inferredVariableType': 'Temperature', 'useInGlobalTemperatureAnalysis': True}
Missing Value: NaN
- year [yr AD]
- temperature [degC]


Ocn-AlboranSea436B.Nieto-Moreno.2013
=========================
Funding: ['FP7/2007-2013)/ERC Grant Agreement #226600']
Funding: ['Research Group 0179']
Funding: ['CTM2009-7715']
Funding: ['Project RNM 05212']
Funding: ['CGL2009-07603']
Funding: ['200800050084447 (MARM)']
Publication: Robust global ocean cooling trend for the pre-industrial Common Era by ['Helen V. McGregor', 'Kandasamy Selvaraj', 'Marie-Alexandrine Sicre', 'Michael N. Evans', 'P. Graham Mortyn', 'Hugues Goosse', 'Jason A. Addison', 'Marit-Solveig Seidenkrantz', 'Vasile Ersek', 'Steven J. Phipps', 'Belen Martrat', 'Delia W. Oppo', 'Guillaume Leduc', 'Helena L. Filipsson', 'Kaustubh Thirumalai']
Publication: PANGAEA by ['V. Nieto-Moreno']
Publication: Climate conditions in the westernmost Mediterranean over the last two millennia: An integrated biomarker approach by ['J. García-Orellana', 'P. Masqué', 'J.S. Sinninghe Damsté', 'V. Willmott', 'F. Martínez-Ruiz', 'V. Nieto-Moreno']
- Paleo Table: Ocn-AlboranSea436B.Nieto-Moreno.2013.paleo1measurement1.csv

      year  temperature
0  1999.07        18.79
1  1993.12        19.38
2  1987.17        19.61
3  1975.26        18.88
4  1963.36        18.74

year {'@id': 'http://linked.earth/lipd/Ocn-AlboranSea436B.Nieto-Moreno.2013.paleo1measurement1.PYTPD2RJATT.year', 'archiveType': 'Marine sediment', 'number': 2, 'description': 'Year AD', 'hasMaxValue': 1999.07, 'hasMeanValue': 1344.463, 'hasMedianValue': 1354.68, 'hasMinValue': 564.36, 'variableName': 'year', 'resolution': {'@id': 'http://linked.earth/lipd/Ocn-AlboranSea436B.Nieto-Moreno.2013.paleo1measurement1.PYTPD2RJATT.year.Resolution', 'hasMaxValue': 32.26, 'hasMeanValue': 29.2798, 'hasMedianValue': 32.26, 'hasMinValue': 5.95, 'units': 'yr AD'}, 'hasStandardVariable': 'year', 'units': 'yr AD', 'TSid': 'PYTPD2RJATT', 'variableType': 'inferred', 'inferredVariableType': 'Year', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Ocn-AlboranSea436B.Nieto-Moreno.2013.txt', 'measurementTableName': 'measurementTable1', 'paleoDataTableName': 'DataQC', 'dataType': 'float', 'measurementTableMD5': '69084e53e71d9a6eae4c570c2607eca6'}
temperature {'@id': 'http://linked.earth/lipd/Ocn-AlboranSea436B.Nieto-Moreno.2013.paleo1measurement1.LPD0e0867fe.temperature', 'calibration': [{'@id': 'http://linked.earth/lipd/Ocn-AlboranSea436B.Nieto-Moreno.2013.paleo1measurement1.LPD0e0867fe.temperature.Calibration', 'equation': "est. SST = (UK'37 - 0.044) / 0.033", 'notes': 'MUE1998: Muller et al. 1998 sediment core top based calibration, n=370, R2=0.958)', 'uncertainty': 'Ocn-AlboranSea436B.Nieto-Moreno.2013.paleo1measurement1.LPD0e0867fe.temperature.Calibration.Uncertainty', 'reference': '10.1016/S0016-7037(98)00097-0'}], 'interpretation': [{'@id': 'http://linked.earth/lipd/Ocn-AlboranSea436B.Nieto-Moreno.2013.paleo1measurement1.LPD0e0867fe.temperature.Interpretation1', 'basis': 'alkenone calibration to SST', 'direction': 'positive', 'scope': 'climate', 'seasonality': 'Annual', 'variable': 'temperature', 'variableDetail': 'sea@surface'}], 'archiveType': 'Marine sediment', 'number': 1, 'description': 'inferred sea-surface temperature', 'hasMaxValue': 20.0, 'hasMeanValue': 19.0642, 'hasMedianValue': 19.05, 'hasMinValue': 18.52, 'variableName': 'temperature', 'notes': 'HVM, BM, 20/4/2016 Mediterranean1572bNieto-Moreno2012__TTR17-1_436B', 'inCompilationBeta': {'@id': 'http://linked.earth/lipd/Pages2kTemperature.66deb3851afb0', 'compilationName': 'Pages2kTemperature', 'compilationVersion': '2_1_1'}, 'proxy': 'alkenone', 'resolution': {'@id': 'http://linked.earth/lipd/Ocn-AlboranSea436B.Nieto-Moreno.2013.paleo1measurement1.LPD0e0867fe.temperature.Resolution', 'hasMaxValue': 32.26, 'hasMeanValue': 29.2798, 'hasMedianValue': 32.26, 'hasMinValue': 5.95, 'units': 'yr AD'}, 'hasStandardVariable': 'temperature', 'uncertainty': 'Ocn-AlboranSea436B.Nieto-Moreno.2013.paleo1measurement1.LPD0e0867fe.temperature.Uncertainty', 'units': 'degC', 'TSid': 'LPD0e0867fe', 'variableType': 'inferred', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Ocn-AlboranSea436B.Nieto-Moreno.2013.txt', 'useInGlobalTemperatureAnalysis': True, 'inferredVariableType': 'Temperature', 'measurementTableName': 'measurementTable1', 'paleoDataTableName': 'DataQC', 'measurementMethod': 'alkenone', 'measurementMaterial': 'alkenone', 'dataType': 'float', 'measurementTableMD5': '69084e53e71d9a6eae4c570c2607eca6', 'pages2kID': 'Ocn_005', 'ocean2kID': 'Mediterranean1572bNieto-Moreno2012__TTR17-1_436B', 'qCCertification': 'BM, MAS, HVM, KT, JAA'}
Missing Value: NaN
- year [yr AD]
- temperature [degC]


Eur-SpannagelCave.Mangini.2005
=========================
Publication: Reconstruction of temperature in the Central Alps during the past 2000 yr from a δ18O stalagmite record by ['C. Spötl', 'A. Mangini', 'P. Verdes']
Publication: World Data Center for Paleoclimatology by ['A. Mangini']
- Paleo Table: Eur-SpannagelCave.Mangini.2005.paleo1measurement1.csv

     year  d18O
0  1935.0 -7.49
1  1932.0 -7.41
2  1930.0 -7.36
3  1929.0 -7.15
4  1929.0 -7.28

year {'@id': 'http://linked.earth/lipd/Eur-SpannagelCave.Mangini.2005.paleo1measurement1.PYTSOOGT8HT.year', 'archiveType': 'Speleothem', 'number': 2, 'description': 'Year AD', 'hasMaxValue': 1935.0, 'hasMeanValue': 1029.1329, 'hasMedianValue': 1035.0, 'hasMinValue': -90.0, 'variableName': 'year', 'resolution': {'@id': 'http://linked.earth/lipd/Eur-SpannagelCave.Mangini.2005.paleo1measurement1.PYTSOOGT8HT.year.Resolution', 'hasMaxValue': 13.4, 'hasMeanValue': 2.8282, 'hasMedianValue': 2.5, 'units': 'yr AD'}, 'hasStandardVariable': 'year', 'units': 'yr AD', 'TSid': 'PYTSOOGT8HT', 'variableType': 'inferred', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Eur-SpannagelCave.Mangini.2005.txt', 'measurementTableName': 'measurementTable1', 'inferredVariableType': 'Year', 'paleoDataTableName': 'measTable', 'dataType': 'float', 'measurementTableMD5': '401fe07a1e24127fee651644aef63781'}
d18O {'@id': 'http://linked.earth/lipd/Eur-SpannagelCave.Mangini.2005.paleo1measurement1.Eur_001.d18O', 'interpretation': [{'@id': 'http://linked.earth/lipd/Eur-SpannagelCave.Mangini.2005.paleo1measurement1.Eur_001.d18O.Interpretation1', 'basis': 'correlation with local meteorological correlation', 'direction': 'negative', 'scope': 'climate', 'seasonality': 'Winter', 'variable': 'temperature', 'variableDetail': 'air@condensationLevel'}], 'archiveType': 'Speleothem', 'number': 1, 'hasMaxValue': -6.8, 'hasMeanValue': -7.5067, 'hasMedianValue': -7.51, 'hasMinValue': -8.3, 'variableName': 'd18O', 'notes': "The uppermost point marks the present-day conditions in Spannagel at +1.8C and y18O= 7.8x. The average temperature in the Alps during the coldest period between 1688 and 1698 coincided with the Maunder Minimum. As derived from Luterbacher's data the average temperature in this period was 1.0 (F0.5) 8C about 1.8 8C lower than in the period between 1995 and 1998.", 'inCompilationBeta': {'@id': 'http://linked.earth/lipd/Pages2kTemperature.66deb3851e7c7', 'compilationName': 'Pages2kTemperature', 'compilationVersion': '2_1_1'}, 'proxy': 'd18O', 'resolution': {'@id': 'http://linked.earth/lipd/Eur-SpannagelCave.Mangini.2005.paleo1measurement1.Eur_001.d18O.Resolution', 'hasMaxValue': 13.4, 'hasMeanValue': 2.8282, 'hasMedianValue': 2.5, 'units': 'yr AD'}, 'hasStandardVariable': 'd18O', 'units': 'permil', 'TSid': 'Eur_001', 'variableType': 'measured', 'qCCertification': 'JPW', 'measurementTableName': 'measurementTable1', 'paleoDataTableName': 'measTable', 'proxyObservationType': 'd18O', 'pages2kID': 'Eur_018', 'useInGlobalTemperatureAnalysis': True, 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Eur-SpannagelCave.Mangini.2005.txt', 'measurementTableMD5': '401fe07a1e24127fee651644aef63781'}
Missing Value: NaN
- year [yr AD]
- d18O [permil]


Ocn-FeniDrift.Richter.2009
=========================
Publication: Late Holocene (0–2.4kaBP) surface water temperature and salinity variability, Feni Drift, NE Atlantic Ocean by ['T.C.E. van Weering', 'T.O. Richter', 'F.J.C. Peeters']
Publication: World Data Center for Paleoclimatology by ['T.O. Richter']
Publication: Robust global ocean cooling trend for the pre-industrial Common Era by ['Helena L. Filipsson', 'Kaustubh Thirumalai', 'Marit-Solveig Seidenkrantz', 'Marie-Alexandrine Sicre', 'Michael N. Evans', 'P. Graham Mortyn', 'Delia W. Oppo', 'Jason A. Addison', 'Steven J. Phipps', 'Belen Martrat', 'Guillaume Leduc', 'Helen V. McGregor', 'Kandasamy Selvaraj', 'Hugues Goosse', 'Vasile Ersek']
- Paleo Table: Ocn-FeniDrift.Richter.2009.paleo1measurement1.csv

   year  Mg/Ca  temperature
0  1998  2.310        12.94
1  1987  1.973        10.99
2  1975  1.901        10.53
3  1962  1.887        10.44
4  1949  2.038        11.39

year {'@id': 'http://linked.earth/lipd/Ocn-FeniDrift.Richter.2009.paleo1measurement1.PYTA482M43E.year', 'archiveType': 'Marine sediment', 'number': 2, 'description': 'Year AD', 'hasMaxValue': 1998.0, 'hasMeanValue': 1000.4904, 'hasMedianValue': 1130.0, 'hasMinValue': -368.0, 'variableName': 'year', 'resolution': {'@id': 'http://linked.earth/lipd/Ocn-FeniDrift.Richter.2009.paleo1measurement1.PYTA482M43E.year.Resolution', 'hasMaxValue': 38.0, 'hasMeanValue': 22.9709, 'hasMedianValue': 22.0, 'hasMinValue': 11.0, 'units': 'yr AD'}, 'hasStandardVariable': 'year', 'units': 'yr AD', 'TSid': 'PYTA482M43E', 'variableType': 'inferred', 'inferredVariableType': 'Year', 'measurementTableName': 'measurementTable1', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Ocn-FeniDrift.Richter.2009-1.txt', 'paleoDataTableName': 'DataQC', 'dataType': 'float', 'measurementTableMD5': '039fb7de0395c2b12df64d2a0dbd51c2'}
Mg/Ca {'@id': 'http://linked.earth/lipd/Ocn-FeniDrift.Richter.2009.paleo1measurement1.LPDbceb5d84.Mg_Ca', 'interpretation': [{'@id': 'http://linked.earth/lipd/Ocn-FeniDrift.Richter.2009.paleo1measurement1.LPDbceb5d84.Mg_Ca.Interpretation1', 'scope': 'climate'}], 'archiveType': 'Marine sediment', 'number': 3, 'description': 'native Mg/Ca ratio from which SST was calculated; values are from foram G. bulloides, and are in units of mmol/mol', 'hasMaxValue': 2.881, 'hasMeanValue': 2.4679, 'hasMedianValue': 2.477, 'hasMinValue': 1.836, 'variableName': 'Mg_Ca', 'notes': '; paleoData_variableName changed - was originally MgCa; paleoData_variableName changed - was originally Mg_Ca; paleoData_variableName changed - was originally Mg_Ca; paleoData_proxyObservationType changed - was originally Mg_Ca', 'inCompilationBeta': {'@id': 'http://linked.earth/lipd/Pages2kTemperature.66deb385216ac', 'compilationName': 'Pages2kTemperature', 'compilationVersion': '2_1_1'}, 'resolution': {'@id': 'http://linked.earth/lipd/Ocn-FeniDrift.Richter.2009.paleo1measurement1.LPDbceb5d84.Mg_Ca.Resolution', 'hasMaxValue': 38.0, 'hasMeanValue': 22.9709, 'hasMedianValue': 22.0, 'hasMinValue': 11.0, 'units': 'yr AD'}, 'hasStandardVariable': 'Mg/Ca', 'TSid': 'LPDbceb5d84', 'variableType': 'measured', 'measurementTableMD5': '039fb7de0395c2b12df64d2a0dbd51c2', 'useInGlobalTemperatureAnalysis': False, 'measurementTableName': 'measurementTable1', 'proxyObservationType': 'Mg/Ca', 'paleoDataTableName': 'DataQC', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Ocn-FeniDrift.Richter.2009-1.txt', 'dataType': 'float'}
temperature {'@id': 'http://linked.earth/lipd/Ocn-FeniDrift.Richter.2009.paleo1measurement1.LPD47182517.temperature', 'calibration': [{'@id': 'http://linked.earth/lipd/Ocn-FeniDrift.Richter.2009.paleo1measurement1.LPD47182517.temperature.Calibration', 'equation': 'Mg/Ca = 0.81 x exp(0.081 x T)', 'notes': 'ANA2003: G. bulloides, based on coretop data from Elderfield and Ganssen, 2000, Nature', 'uncertainty': 'Ocn-FeniDrift.Richter.2009.paleo1measurement1.LPD47182517.temperature.Calibration.Uncertainty', 'reference': '10.1029/2002PA000846'}], 'interpretation': [{'@id': 'http://linked.earth/lipd/Ocn-FeniDrift.Richter.2009.paleo1measurement1.LPD47182517.temperature.Interpretation1', 'basis': 'Mg/Ca calibration to SST', 'direction': 'positive', 'scope': 'climate', 'seasonality': 'Apr-Jul', 'variable': 'temperature', 'variableDetail': 'sea@surface'}], 'archiveType': 'Marine sediment', 'number': 1, 'description': 'inferred sea-surface temperature', 'hasMaxValue': 15.66, 'hasMeanValue': 13.6974, 'hasMedianValue': 13.8, 'hasMinValue': 10.1, 'variableName': 'temperature', 'notes': 'HVM, BM, 20/4/2016 Atlantic0058Richter2009__ENAM9606,M200309_Mg/Ca', 'inCompilationBeta': {'@id': 'http://linked.earth/lipd/Pages2kTemperature.66deb385215e6', 'compilationName': 'Pages2kTemperature', 'compilationVersion': '2_1_1'}, 'proxy': 'Mg/Ca', 'resolution': {'@id': 'http://linked.earth/lipd/Ocn-FeniDrift.Richter.2009.paleo1measurement1.LPD47182517.temperature.Resolution', 'hasMaxValue': 38.0, 'hasMeanValue': 22.9709, 'hasMedianValue': 22.0, 'hasMinValue': 11.0, 'units': 'yr AD'}, 'hasStandardVariable': 'temperature', 'uncertainty': 'Ocn-FeniDrift.Richter.2009.paleo1measurement1.LPD47182517.temperature.Uncertainty', 'units': 'degC', 'TSid': 'LPD47182517', 'variableType': 'inferred', 'qCCertification': 'HVM, KT, BM, JAA', 'measurementMaterial': 'foram Mg/Ca (G. bulloides)', 'paleoDataTableName': 'DataQC', 'dataType': 'float', 'measurementTableName': 'measurementTable1', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Ocn-FeniDrift.Richter.2009-1.txt', 'pages2kID': 'Ocn_020', 'inferredVariableType': 'Temperature', 'measurementTableMD5': '039fb7de0395c2b12df64d2a0dbd51c2', 'iso2kUI': 'MS09TRFD01', 'ocean2kID': 'Atlantic0058Richter2009__ENAM9606,M200309', 'measurementMethod': 'Mg/Ca', 'useInGlobalTemperatureAnalysis': True}
Missing Value: NaN
- year [yr AD]
- Mg_Ca
- temperature [degC]
- Paleo Table: Ocn-FeniDrift.Richter.2009.paleo2measurement1.csv

   depthTop  temperature  depthBottom  year  Mg/Ca    notes
0       0.5        12.94          0.5  1998  2.310  M200309
1       1.5        10.99          1.5  1987  1.973  M200309
2       2.5        10.53          2.5  1975  1.901  M200309
3       3.5        10.44          3.5  1962  1.887  M200309
4       4.5        11.39          4.5  1949  2.038  M200309

depthTop {'@id': 'http://linked.earth/lipd/Ocn-FeniDrift.Richter.2009.paleo2measurement1.LPD873b43d0.depth_top', 'interpretation': [{'@id': 'http://linked.earth/lipd/Ocn-FeniDrift.Richter.2009.paleo2measurement1.LPD873b43d0.depth_top.Interpretation1', 'scope': 'climate'}], 'archiveType': 'Marine sediment', 'number': 1, 'description': 'depth', 'hasMaxValue': 84.5, 'hasMeanValue': 36.4712, 'hasMedianValue': 33.0, 'hasMinValue': 0.5, 'variableName': 'depth_top', 'notes': 'These are the original, not quality controlled data. O2kLR recommends only using the Quality controlled data.', 'inCompilationBeta': {'@id': 'http://linked.earth/lipd/Pages2kTemperature.66deb3852172a', 'compilationName': 'Pages2kTemperature', 'compilationVersion': '2_1_1'}, 'resolution': {'@id': 'http://linked.earth/lipd/Ocn-FeniDrift.Richter.2009.paleo2measurement1.LPD873b43d0.depth_top.Resolution', 'hasMaxValue': 38.0, 'hasMeanValue': 22.9709, 'hasMedianValue': 22.0, 'hasMinValue': 11.0, 'units': 'yr AD'}, 'hasStandardVariable': 'depthTop', 'units': 'cm', 'TSid': 'LPD873b43d0', 'variableType': 'measured', 'dataType': 'float', 'measurementTableName': 'measurementTable1', 'paleoDataTableName': 'Dataoriginal', 'useInGlobalTemperatureAnalysis': False, 'measurementTableMD5': '7c005b7c718ad460a5e2bfcb456d06f5', 'detail': 'top of sample', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Ocn-FeniDrift.Richter.2009-2.txt'}
temperature {'@id': 'http://linked.earth/lipd/Ocn-FeniDrift.Richter.2009.paleo2measurement1.LPDb7290ea4.temperature', 'interpretation': [{'@id': 'http://linked.earth/lipd/Ocn-FeniDrift.Richter.2009.paleo2measurement1.LPDb7290ea4.temperature.Interpretation1', 'basis': 'Mg/Ca calibration to SST', 'direction': 'positive', 'scope': 'climate', 'seasonality': 'Apr-Jul', 'variable': 'temperature', 'variableDetail': 'sea_surface'}], 'archiveType': 'Marine sediment', 'number': 4, 'description': 'Mg/Ca SST', 'hasMaxValue': 15.66, 'hasMeanValue': 13.6974, 'hasMedianValue': 13.8, 'hasMinValue': 10.1, 'variableName': 'temperature', 'notes': 'These are the original, not quality controlled data. O2kLR recommends only using the Quality controlled data.Identical to LPD47182517', 'inCompilationBeta': {'@id': 'http://linked.earth/lipd/Pages2kTemperature.66deb38521863', 'compilationName': 'Pages2kTemperature', 'compilationVersion': '2_1_1'}, 'resolution': {'@id': 'http://linked.earth/lipd/Ocn-FeniDrift.Richter.2009.paleo2measurement1.LPDb7290ea4.temperature.Resolution', 'hasMaxValue': 38.0, 'hasMeanValue': 22.9709, 'hasMedianValue': 22.0, 'hasMinValue': 11.0, 'units': 'yr AD'}, 'hasStandardVariable': 'temperature', 'uncertainty': 'Ocn-FeniDrift.Richter.2009.paleo2measurement1.LPDb7290ea4.temperature.Uncertainty', 'units': 'degC', 'TSid': 'LPDb7290ea4', 'variableType': 'inferred', 'dataType': 'float', 'qCCertification': 'KT', 'paleoDataTableName': 'Dataoriginal', 'measurementTableMD5': '7c005b7c718ad460a5e2bfcb456d06f5', 'measurementMaterial': 'Globigerina bulloides', 'inferredVariableType': 'Temperature', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Ocn-FeniDrift.Richter.2009-2.txt', 'measurementMethod': 'Converted into calcification temperatures with the species-specific equation of Anand et al. (2003) based on data from Elderfield and Ganssen (2000)  (ANA2003)', 'useInGlobalTemperatureAnalysis': False, 'measurementTableName': 'measurementTable1'}
depthBottom {'@id': 'http://linked.earth/lipd/Ocn-FeniDrift.Richter.2009.paleo2measurement1.LPD071f9a58.depth_bottom', 'interpretation': [{'@id': 'http://linked.earth/lipd/Ocn-FeniDrift.Richter.2009.paleo2measurement1.LPD071f9a58.depth_bottom.Interpretation1', 'scope': 'climate'}], 'archiveType': 'Marine sediment', 'number': 3, 'description': 'depth', 'hasMaxValue': 84.5, 'hasMeanValue': 36.4712, 'hasMedianValue': 33.0, 'hasMinValue': 0.5, 'variableName': 'depth_bottom', 'notes': 'These are the original, not quality controlled data. O2kLR recommends only using the Quality controlled data.', 'inCompilationBeta': {'@id': 'http://linked.earth/lipd/Pages2kTemperature.66deb385217f0', 'compilationName': 'Pages2kTemperature', 'compilationVersion': '2_1_1'}, 'resolution': {'@id': 'http://linked.earth/lipd/Ocn-FeniDrift.Richter.2009.paleo2measurement1.LPD071f9a58.depth_bottom.Resolution', 'hasMaxValue': 38.0, 'hasMeanValue': 22.9709, 'hasMedianValue': 22.0, 'hasMinValue': 11.0, 'units': 'yr AD'}, 'hasStandardVariable': 'depthBottom', 'units': 'cm', 'TSid': 'LPD071f9a58', 'variableType': 'measured', 'measurementTableMD5': '7c005b7c718ad460a5e2bfcb456d06f5', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Ocn-FeniDrift.Richter.2009-2.txt', 'useInGlobalTemperatureAnalysis': False, 'detail': 'bottom of sample', 'dataType': 'float', 'measurementTableName': 'measurementTable1', 'paleoDataTableName': 'Dataoriginal'}
year {'@id': 'http://linked.earth/lipd/Ocn-FeniDrift.Richter.2009.paleo2measurement1.PYTHS7WC58V.year', 'archiveType': 'Marine sediment', 'number': 2, 'description': 'Year AD', 'hasMaxValue': 1998.0, 'hasMeanValue': 1000.4904, 'hasMedianValue': 1130.0, 'hasMinValue': -368.0, 'variableName': 'year', 'resolution': {'@id': 'http://linked.earth/lipd/Ocn-FeniDrift.Richter.2009.paleo2measurement1.PYTHS7WC58V.year.Resolution', 'hasMaxValue': 38.0, 'hasMeanValue': 22.9709, 'hasMedianValue': 22.0, 'hasMinValue': 11.0, 'units': 'yr AD'}, 'hasStandardVariable': 'year', 'units': 'yr AD', 'TSid': 'PYTHS7WC58V', 'variableType': 'inferred', 'inferredVariableType': 'Year', 'measurementTableName': 'measurementTable1', 'paleoDataTableName': 'Dataoriginal', 'measurementTableMD5': '7c005b7c718ad460a5e2bfcb456d06f5', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Ocn-FeniDrift.Richter.2009-2.txt', 'dataType': 'float'}
Mg/Ca {'@id': 'http://linked.earth/lipd/Ocn-FeniDrift.Richter.2009.paleo2measurement1.LPDba471ae7.Mg_Ca', 'interpretation': [{'@id': 'http://linked.earth/lipd/Ocn-FeniDrift.Richter.2009.paleo2measurement1.LPDba471ae7.Mg_Ca.Interpretation1', 'scope': 'climate'}], 'archiveType': 'Marine sediment', 'number': 5, 'description': 'native Mg/Ca ratio from which SST was calculated; values are from foram G. bulloides, and are in units of mmol/mol', 'hasMaxValue': 2.881, 'hasMeanValue': 2.4679, 'hasMedianValue': 2.477, 'hasMinValue': 1.836, 'variableName': 'Mg_Ca', 'notes': 'These are the original, not quality controlled data. O2kLR recommends only using the Quality controlled data.', 'inCompilationBeta': {'@id': 'http://linked.earth/lipd/Pages2kTemperature.66deb385218da', 'compilationName': 'Pages2kTemperature', 'compilationVersion': '2_1_1'}, 'resolution': {'@id': 'http://linked.earth/lipd/Ocn-FeniDrift.Richter.2009.paleo2measurement1.LPDba471ae7.Mg_Ca.Resolution', 'hasMaxValue': 38.0, 'hasMeanValue': 22.9709, 'hasMedianValue': 22.0, 'hasMinValue': 11.0, 'units': 'yr AD'}, 'hasStandardVariable': 'Mg/Ca', 'TSid': 'LPDba471ae7', 'variableType': 'measured', 'dataType': 'float', 'measurementTableName': 'measurementTable1', 'proxyObservationType': 'Mg/Ca', 'paleoDataTableName': 'Dataoriginal', 'measurementTableMD5': '7c005b7c718ad460a5e2bfcb456d06f5', 'useInGlobalTemperatureAnalysis': False, 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Ocn-FeniDrift.Richter.2009-2.txt'}
notes {'@id': 'http://linked.earth/lipd/Ocn-FeniDrift.Richter.2009.paleo2measurement1.LPD6e0eacd1.notes', 'interpretation': [{'@id': 'http://linked.earth/lipd/Ocn-FeniDrift.Richter.2009.paleo2measurement1.LPD6e0eacd1.notes.Interpretation1', 'scope': 'climate'}], 'archiveType': 'Marine sediment', 'number': 6, 'description': 'original composite dataset from Richter et al. (2009) - PLEASE USE QC DATA FOR ANALYSIS!!!!', 'variableName': 'notes', 'notes': 'These are the original, not quality controlled data. O2kLR recommends only using the Quality controlled data.', 'inCompilationBeta': {'@id': 'http://linked.earth/lipd/Pages2kTemperature.66deb38521933', 'compilationName': 'Pages2kTemperature', 'compilationVersion': '2_1_1'}, 'resolution': {'@id': 'http://linked.earth/lipd/Ocn-FeniDrift.Richter.2009.paleo2measurement1.LPD6e0eacd1.notes.Resolution', 'hasMaxValue': 38.0, 'hasMeanValue': 22.9709, 'hasMedianValue': 22.0, 'hasMinValue': 11.0, 'units': 'yr AD'}, 'hasStandardVariable': 'notes', 'TSid': 'LPD6e0eacd1', 'variableType': 'measured', 'dataType': 'str', 'measurementTableName': 'measurementTable1', 'paleoDataTableName': 'Dataoriginal', 'measurementTableMD5': '7c005b7c718ad460a5e2bfcb456d06f5', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Ocn-FeniDrift.Richter.2009-2.txt', 'useInGlobalTemperatureAnalysis': False}
Missing Value: NaN
- depth_top [cm]
- temperature [degC]
- depth_bottom [cm]
- year [yr AD]
- Mg_Ca
- notes


Eur-LakeSilvaplana.Trachsel.2010
=========================
Publication: Scanning reflectance spectroscopy (380–730 nm): a novel method for quantitative high-resolution climate reconstructions from minerogenic lake sediments by ['B. Rein', 'M. Trachsel', 'M. Grosjean', 'D. Schnyder', 'C. Kamenik']
Publication: World Data Center for Paleoclimatology by ['M. Trachsel']
- Paleo Table: Eur-LakeSilvaplana.Trachsel.2010.paleo1measurement1.csv

   temperature  year
0     0.181707  1175
1     0.111083  1176
2     0.001382  1177
3    -0.008682  1178
4    -0.048438  1179

temperature {'@id': 'http://linked.earth/lipd/Eur-LakeSilvaplana.Trachsel.2010.paleo1measurement1.Eur_002.temperature', 'calibration': [{'@id': 'http://linked.earth/lipd/Eur-LakeSilvaplana.Trachsel.2010.paleo1measurement1.Eur_002.temperature.Calibration', 'uncertainty': 'Eur-LakeSilvaplana.Trachsel.2010.paleo1measurement1.Eur_002.temperature.Calibration.Uncertainty'}], 'interpretation': [{'@id': 'http://linked.earth/lipd/Eur-LakeSilvaplana.Trachsel.2010.paleo1measurement1.Eur_002.temperature.Interpretation1', 'basis': 'correlation with local meteorological correlation', 'direction': 'positive', 'scope': 'climate', 'seasonality': 'Summer', 'variable': 'temperature', 'variableDetail': 'air@surface'}], 'archiveType': 'Lake sediment', 'number': 1, 'hasMaxValue': 0.5856, 'hasMeanValue': 0.0032, 'hasMedianValue': 0.01, 'hasMinValue': -0.5195, 'variableName': 'temperature', 'notes': 'We used multiple linear regression (MLR) to establish a calibration model that explains 84% of the variance of summer (JJAS) temperature during the calibration period 1864_1950. We then applied the calibration model downcore to develop a quantitative summer temperature reconstruction extending back to AD 1177.', 'inCompilationBeta': {'@id': 'http://linked.earth/lipd/Pages2kTemperature.66deb3852699d', 'compilationName': 'Pages2kTemperature', 'compilationVersion': '2_1_1'}, 'proxy': 'reflectance', 'resolution': {'@id': 'http://linked.earth/lipd/Eur-LakeSilvaplana.Trachsel.2010.paleo1measurement1.Eur_002.temperature.Resolution', 'hasMaxValue': 1.0, 'hasMeanValue': 1.0, 'hasMedianValue': 1.0, 'hasMinValue': 1.0, 'units': 'yr AD'}, 'hasStandardVariable': 'temperature', 'units': 'degC', 'TSid': 'Eur_002', 'variableType': 'inferred', 'measurementTableMD5': 'ccebf8e7d473c06878096efb0dd8e710', 'pages2kID': 'Eur_015', 'qCCertification': 'JPW', 'measurementTableName': 'measurementTable1', 'inferredVariableType': 'Temperature', 'useInGlobalTemperatureAnalysis': True, 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Eur-LakeSilvaplana.Trachsel.2010.txt', 'paleoDataTableName': 'measTable'}
year {'@id': 'http://linked.earth/lipd/Eur-LakeSilvaplana.Trachsel.2010.paleo1measurement1.PYT1E4X3DDF.year', 'archiveType': 'Lake sediment', 'number': 2, 'description': 'Year AD', 'hasMaxValue': 1949.0, 'hasMeanValue': 1562.0, 'hasMedianValue': 1562.0, 'hasMinValue': 1175.0, 'variableName': 'year', 'resolution': {'@id': 'http://linked.earth/lipd/Eur-LakeSilvaplana.Trachsel.2010.paleo1measurement1.PYT1E4X3DDF.year.Resolution', 'hasMaxValue': 1.0, 'hasMeanValue': 1.0, 'hasMedianValue': 1.0, 'hasMinValue': 1.0, 'units': 'yr AD'}, 'hasStandardVariable': 'year', 'units': 'yr AD', 'TSid': 'PYT1E4X3DDF', 'variableType': 'inferred', 'dataType': 'float', 'measurementTableMD5': 'ccebf8e7d473c06878096efb0dd8e710', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Eur-LakeSilvaplana.Trachsel.2010.txt', 'measurementTableName': 'measurementTable1', 'paleoDataTableName': 'measTable', 'inferredVariableType': 'Year'}
Missing Value: NaN
- temperature [degC]
- year [yr AD]


Ocn-PedradeLume-CapeVerdeIslands.Moses.2006
=========================
Publication: Evidence of multidecadal salinity variability in the eastern tropical North Atlantic by ['Christopher S. Moses', 'Brad E. Rosenheim', 'Peter K. Swart']
Publication: World Data Center for Paleoclimatology by ['C.S. Moses']
- Paleo Table: Ocn-PedradeLume-CapeVerdeIslands.Moses.2006.paleo1measurement1.csv

      year  d18O
0  1928.96 -3.11
1  1929.04 -2.90
2  1929.12 -2.88
3  1929.21 -2.73
4  1929.29 -2.73

year {'@id': 'http://linked.earth/lipd/Ocn-PedradeLume-CapeVerdeIslands.Moses.2006.paleo1measurement1.PYT296KN772.year', 'archiveType': 'Coral', 'number': 2, 'description': 'Year AD', 'hasMaxValue': 2002.21, 'hasMeanValue': 1965.5805, 'hasMedianValue': 1965.58, 'hasMinValue': 1928.96, 'variableName': 'year', 'resolution': {'@id': 'http://linked.earth/lipd/Ocn-PedradeLume-CapeVerdeIslands.Moses.2006.paleo1measurement1.PYT296KN772.year.Resolution', 'hasMaxValue': 0.09, 'hasMeanValue': 0.0833, 'hasMedianValue': 0.08, 'hasMinValue': 0.08, 'units': 'yr AD'}, 'hasStandardVariable': 'year', 'units': 'yr AD', 'TSid': 'PYT296KN772', 'variableType': 'inferred', 'measurementTableName': 'measurementTable1', 'paleoDataTableName': 'measTable', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Ocn-PedradeLume-CapeVerdeIslands.Moses.2006.txt', 'measurementTableMD5': '42506edb76d06552ac645b056096079d', 'dataType': 'float', 'inferredVariableType': 'Year'}
d18O {'@id': 'http://linked.earth/lipd/Ocn-PedradeLume-CapeVerdeIslands.Moses.2006.paleo1measurement1.Ocean2kHR_107.d18O', 'interpretation': [{'@id': 'http://linked.earth/lipd/Ocn-PedradeLume-CapeVerdeIslands.Moses.2006.paleo1measurement1.Ocean2kHR_107.d18O.Interpretation1', 'direction': 'negative', 'scope': 'climate', 'seasonality': 'subannual', 'variable': 'temperature', 'variableDetail': 'sea@surface'}], 'archiveType': 'Coral', 'number': 1, 'hasMaxValue': -2.1, 'hasMeanValue': -3.0033, 'hasMedianValue': -2.99, 'hasMinValue': -3.92, 'variableName': 'd18O', 'notes': '; climateInterpretation_seasonality changed - was originally monthly', 'inCompilationBeta': {'@id': 'http://linked.earth/lipd/Pages2kTemperature.66deb3852997e', 'compilationName': 'Pages2kTemperature', 'compilationVersion': '2_1_1'}, 'proxy': 'd18O', 'resolution': {'@id': 'http://linked.earth/lipd/Ocn-PedradeLume-CapeVerdeIslands.Moses.2006.paleo1measurement1.Ocean2kHR_107.d18O.Resolution', 'hasMaxValue': 0.09, 'hasMeanValue': 0.0833, 'hasMedianValue': 0.08, 'hasMinValue': 0.08, 'units': 'yr AD'}, 'hasStandardVariable': 'd18O', 'units': 'permil', 'TSid': 'Ocean2kHR_107', 'variableType': 'measured', 'measurementTableMD5': '42506edb76d06552ac645b056096079d', 'qCCertification': 'KHK, NJA', 'measurementTableName': 'measurementTable1', 'paleoDataTableName': 'measTable', 'proxyObservationType': 'd18O', 'sensorSpecies': 'Siderastrea radians', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Ocn-PedradeLume-CapeVerdeIslands.Moses.2006.txt', 'pages2kID': 'Ocn_146', 'iso2kUI': 'CO06MOPE01A', 'sensorGenus': 'Siderastrea', 'useInGlobalTemperatureAnalysis': True}
Missing Value: NaN
- year [yr AD]
- d18O [permil]


Ocn-SinaiPeninsula,RedSea.Moustafa.2000
=========================
Publication: Tropical sea surface temperatures for the past four centuries reconstructed from coral archives by ['Jessica E. Tierney', 'K. Halimeda Kilbourne', 'Nerilie J. Abram', 'Henry C. Wu', 'Michael N. Evans', 'Jens Zinke', 'Casey P. Saenger', 'Cyril Giry', 'Kevin J. Anchukaitis']
Publication: PANGAEA by ['Y.A. Moustafa']
Publication: Mid-Holocene stable isotope record of corals from the northern Red Sea by ['Yaser Ahmed Moustafa', 'Yossi Loya', 'Jürgen Pätzold', 'Gerold Wefer']
- Paleo Table: Ocn-SinaiPeninsula,RedSea.Moustafa.2000.paleo1measurement1.csv

   d18O     year
0 -3.05  1993.12
1 -3.63  1992.86
2 -3.53  1992.66
3 -3.47  1992.39
4 -3.10  1992.12

d18O {'@id': 'http://linked.earth/lipd/Ocn-SinaiPeninsula_RedSea.Moustafa.2000.paleo1measurement1.Ocean2kHR_018.d18O', 'interpretation': [{'@id': 'http://linked.earth/lipd/Ocn-SinaiPeninsula_RedSea.Moustafa.2000.paleo1measurement1.Ocean2kHR_018.d18O.Interpretation1', 'direction': 'negative', 'scope': 'climate', 'seasonality': 'subannual', 'variable': 'temperature', 'variableDetail': 'sea@surface'}], 'archiveType': 'Coral', 'number': 1, 'hasMaxValue': -2.53, 'hasMeanValue': -3.4205, 'hasMedianValue': -3.46, 'hasMinValue': -4.09, 'variableName': 'd18O', 'notes': '; climateInterpretation_seasonality changed - was originally bimonthly', 'inCompilationBeta': {'@id': 'http://linked.earth/lipd/Pages2kTemperature.66deb3852c674', 'compilationName': 'Pages2kTemperature', 'compilationVersion': '2_1_1'}, 'proxy': 'd18O', 'resolution': {'@id': 'http://linked.earth/lipd/Ocn-SinaiPeninsula_RedSea.Moustafa.2000.paleo1measurement1.Ocean2kHR_018.d18O.Resolution', 'hasMaxValue': 0.5, 'hasMeanValue': 0.1871, 'hasMedianValue': 0.18, 'hasMinValue': 0.07, 'units': 'yr AD'}, 'hasStandardVariable': 'd18O', 'units': 'permil', 'TSid': 'Ocean2kHR_018', 'variableType': 'measured', 'qCCertification': 'NJA', 'sensorGenus': 'Porites', 'sensorSpecies': 'NA', 'measurementTableMD5': '448e8bc94a5596bc76c2b43afd2e20cd', 'ocean2kID': 'IndianRusUmSiddMoustafa2000Rus93a', 'useInGlobalTemperatureAnalysis': True, 'pages2kID': 'Ocn_082', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Ocn-SinaiPeninsulaRedSea.Moustafa.2000.txt', 'iso2kUI': 'CO00MOSP01A', 'paleoDataTableName': 'measTable', 'proxyObservationType': 'd18O', 'measurementTableName': 'measurementTable1'}
year {'@id': 'http://linked.earth/lipd/Ocn-SinaiPeninsula_RedSea.Moustafa.2000.paleo1measurement1.PYTGGLQ9T54.year', 'archiveType': 'Coral', 'number': 2, 'description': 'Year AD', 'hasMaxValue': 1993.12, 'hasMeanValue': 1945.0443, 'hasMedianValue': 1944.735, 'hasMinValue': 1897.12, 'variableName': 'year', 'resolution': {'@id': 'http://linked.earth/lipd/Ocn-SinaiPeninsula_RedSea.Moustafa.2000.paleo1measurement1.PYTGGLQ9T54.year.Resolution', 'hasMaxValue': 0.5, 'hasMeanValue': 0.1871, 'hasMedianValue': 0.18, 'hasMinValue': 0.07, 'units': 'yr AD'}, 'hasStandardVariable': 'year', 'units': 'yr AD', 'TSid': 'PYTGGLQ9T54', 'variableType': 'inferred', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Ocn-SinaiPeninsulaRedSea.Moustafa.2000.txt', 'measurementTableMD5': '448e8bc94a5596bc76c2b43afd2e20cd', 'dataType': 'float', 'inferredVariableType': 'Year', 'measurementTableName': 'measurementTable1', 'paleoDataTableName': 'measTable'}
Missing Value: NaN
- d18O [permil]
- year [yr AD]


Eur-NorthernSpain.Martin-Chivelet.2011
=========================
Publication: World Data Center for Paleoclimatology by ['J. Martín-Chivelet']
Publication: Land surface temperature changes in northern Iberia since 4000 yr BP, based on δ13C of speleothems by ['María J. Turrero', 'Ana I. Ortega', 'R. Lawrence Edwards', 'M. Belén Muñoz-García', 'Javier Martín-Chivelet']
- Paleo Table: Eur-NorthernSpain.Martin-Chivelet.2011.paleo1measurement1.csv

   d18O  year
0  0.94  2000
1  0.80  1987
2  0.23  1983
3  0.17  1978
4  0.51  1975

d18O {'@id': 'http://linked.earth/lipd/Eur-NorthernSpain.Martin-Chivelet.2011.paleo1measurement1.Eur_008.d18O', 'interpretation': [{'@id': 'http://linked.earth/lipd/Eur-NorthernSpain.Martin-Chivelet.2011.paleo1measurement1.Eur_008.d18O.Interpretation1', 'basis': 'correlation with local meteorological correlation', 'direction': 'positive', 'scope': 'climate', 'seasonality': 'Summer', 'variable': 'temperature', 'variableDetail': 'air@condensationLevel'}], 'archiveType': 'Speleothem', 'number': 1, 'hasMaxValue': 0.94, 'hasMeanValue': -0.0001, 'hasMedianValue': -0.02, 'hasMinValue': -0.55, 'variableName': 'd18O', 'notes': 'The positive correlation between 013C series of the stalagmites and the surface temperature series shown in the previous section is robust in the three samples but requires some further discussion.', 'inCompilationBeta': {'@id': 'http://linked.earth/lipd/Pages2kTemperature.66deb3852f9d5', 'compilationName': 'Pages2kTemperature', 'compilationVersion': '2_1_1'}, 'proxy': 'd18O', 'resolution': {'@id': 'http://linked.earth/lipd/Eur-NorthernSpain.Martin-Chivelet.2011.paleo1measurement1.Eur_008.d18O.Resolution', 'hasMaxValue': 19.0, 'hasMeanValue': 4.5824, 'hasMedianValue': 3.0, 'units': 'yr AD'}, 'hasStandardVariable': 'd18O', 'units': 'permil', 'TSid': 'Eur_008', 'variableType': 'measured', 'paleoDataTableName': 'measTable', 'pages2kID': 'Eur_017', 'measurementTableMD5': '75fac32fdabe77b07189cb1f64ad9437', 'useInGlobalTemperatureAnalysis': True, 'measurementTableName': 'measurementTable1', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Eur-NorthernSpain.Martn-Chivelet.2011.txt', 'qCCertification': 'JPW', 'proxyObservationType': 'd18O'}
year {'@id': 'http://linked.earth/lipd/Eur-NorthernSpain.Martin-Chivelet.2011.paleo1measurement1.PYTE7VH7UMO.year', 'archiveType': 'Speleothem', 'number': 2, 'description': 'Year AD', 'hasMaxValue': 2000.0, 'hasMeanValue': 537.2297, 'hasMedianValue': 644.0, 'hasMinValue': -1949.0, 'variableName': 'year', 'resolution': {'@id': 'http://linked.earth/lipd/Eur-NorthernSpain.Martin-Chivelet.2011.paleo1measurement1.PYTE7VH7UMO.year.Resolution', 'hasMaxValue': 19.0, 'hasMeanValue': 4.5824, 'hasMedianValue': 3.0, 'units': 'yr AD'}, 'hasStandardVariable': 'year', 'units': 'yr AD', 'TSid': 'PYTE7VH7UMO', 'variableType': 'inferred', 'measurementTableName': 'measurementTable1', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Eur-NorthernSpain.Martn-Chivelet.2011.txt', 'inferredVariableType': 'Year', 'paleoDataTableName': 'measTable', 'dataType': 'float', 'measurementTableMD5': '75fac32fdabe77b07189cb1f64ad9437'}
Missing Value: NaN
- d18O [permil]
- year [yr AD]


Arc-Kongressvatnet.D'Andrea.2012
=========================
Publication: Mild Little Ice Age and unprecedented recent warmth in an 1800 year lake sediment record from Svalbard by ['R. S. Bradley', 'M. Retelle', 'N. L. Balascio', 'D. A. Vaillencourt', 'A. Werner', "W. J. D'Andrea", 'S. R. Roof']
Publication: World Data Center for Paleoclimatology by ["W.J. D'Andrea"]
- Paleo Table: Arc-Kongressvatnet.D'Andrea.2012.paleo1measurement1.csv

   Uk37  year  temperature
0 -0.65  2008          5.9
1 -0.67  2004          5.1
2 -0.65  2000          6.1
3 -0.67  1996          5.3
4 -0.69  1990          4.3

Uk37 {'@id': 'http://linked.earth/lipd/Arc-Kongressvatnet.D_Andrea.2012.paleo1measurement1.Arc_077.Uk37', 'interpretation': [{'@id': 'http://linked.earth/lipd/Arc-Kongressvatnet.D_Andrea.2012.paleo1measurement1.Arc_077.Uk37.Interpretation1', 'scope': 'climate'}], 'archiveType': 'Lake sediment', 'number': 1, 'description': 'depth', 'hasMaxValue': -0.65, 'hasMeanValue': -0.7205, 'hasMedianValue': -0.72, 'hasMinValue': -0.77, 'variableName': 'Uk37', 'inCompilationBeta': {'@id': 'http://linked.earth/lipd/Pages2kTemperature.66deb385325d7', 'compilationName': 'Pages2kTemperature', 'compilationVersion': '2_1_1'}, 'resolution': {'@id': 'http://linked.earth/lipd/Arc-Kongressvatnet.D_Andrea.2012.paleo1measurement1.Arc_077.Uk37.Resolution', 'hasMaxValue': 99.0, 'hasMeanValue': 16.2936, 'hasMedianValue': 10.0, 'hasMinValue': 3.0, 'units': 'yr AD'}, 'hasStandardVariable': 'Uk37', 'TSid': 'Arc_077', 'variableType': 'measured', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Arc-Kongressvatnet.DAndrea.2012.txt', 'dataType': 'float', 'measurementTableName': 'measurementTable1', 'useInGlobalTemperatureAnalysis': False, 'measurementTableMD5': 'a4edf527eac8c98092328a7f2f69e055', 'paleoDataTableName': 'Data', 'proxyObservationType': 'Uk37'}
year {'@id': 'http://linked.earth/lipd/Arc-Kongressvatnet.D_Andrea.2012.paleo1measurement1.PYTOAVDFCGU.year', 'archiveType': 'Lake sediment', 'number': 2, 'description': 'Year AD', 'hasMaxValue': 2008.0, 'hasMeanValue': 1428.2727, 'hasMedianValue': 1520.0, 'hasMinValue': 232.0, 'variableName': 'year', 'resolution': {'@id': 'http://linked.earth/lipd/Arc-Kongressvatnet.D_Andrea.2012.paleo1measurement1.PYTOAVDFCGU.year.Resolution', 'hasMaxValue': 99.0, 'hasMeanValue': 16.2936, 'hasMedianValue': 10.0, 'hasMinValue': 3.0, 'units': 'yr AD'}, 'hasStandardVariable': 'year', 'units': 'yr AD', 'TSid': 'PYTOAVDFCGU', 'variableType': 'inferred', 'paleoDataTableName': 'Data', 'dataType': 'float', 'inferredVariableType': 'Year', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Arc-Kongressvatnet.DAndrea.2012.txt', 'measurementTableName': 'measurementTable1', 'measurementTableMD5': 'a4edf527eac8c98092328a7f2f69e055'}
temperature {'@id': 'http://linked.earth/lipd/Arc-Kongressvatnet.D_Andrea.2012.paleo1measurement1.Arc_078.temperature', 'calibration': [{'@id': 'http://linked.earth/lipd/Arc-Kongressvatnet.D_Andrea.2012.paleo1measurement1.Arc_078.temperature.Calibration', 'uncertainty': "Arc-Kongressvatnet.D'Andrea.2012.paleo1measurement1.Arc_078.temperature.Calibration.Uncertainty", 'reference': '10.1130/G33365.1'}], 'interpretation': [{'@id': 'http://linked.earth/lipd/Arc-Kongressvatnet.D_Andrea.2012.paleo1measurement1.Arc_078.temperature.Interpretation1', 'basis': 'calibrtaion with alkenone paleothermometer', 'direction': 'positive', 'scope': 'climate', 'variable': 'temperature', 'variableDetail': 'lake@surface'}], 'archiveType': 'Lake sediment', 'number': 3, 'description': 'inferred temperature', 'hasMaxValue': 6.1, 'hasMeanValue': 3.2845, 'hasMedianValue': 3.15, 'hasMinValue': 1.3, 'variableName': 'temperature', 'notes': 'strong correlation. However, opposite long-term (orbital) trend to most other Arctic records (FCL)', 'inCompilationBeta': {'@id': 'http://linked.earth/lipd/Pages2kTemperature.66deb385326ab', 'compilationName': 'Pages2kTemperature', 'compilationVersion': '2_1_1'}, 'proxy': 'alkenone', 'resolution': {'@id': 'http://linked.earth/lipd/Arc-Kongressvatnet.D_Andrea.2012.paleo1measurement1.Arc_078.temperature.Resolution', 'hasMaxValue': 99.0, 'hasMeanValue': 16.2936, 'hasMedianValue': 10.0, 'hasMinValue': 3.0, 'units': 'yr AD'}, 'hasStandardVariable': 'temperature', 'units': 'degC', 'TSid': 'Arc_078', 'variableType': 'inferred', 'measurementTableMD5': 'a4edf527eac8c98092328a7f2f69e055', 'qCCertification': 'DVD, JPW', 'paleoDataTableName': 'Data', 'detail': 'Reconstructed JJA temperature', 'dataType': 'float', 'pages2kID': 'Arc_069', 'inferredVariableType': 'Temperature', 'useInGlobalTemperatureAnalysis': True, 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Arc-Kongressvatnet.DAndrea.2012.txt', 'measurementTableName': 'measurementTable1'}
Missing Value: NaN
- Uk37
- year [yr AD]
- temperature [degC]


Eur-CoastofPortugal.Abrantes.2011
=========================
Publication: Climate of the last millennium at the southern pole of the North Atlantic Oscillation: an inner-shelf sediment record of flooding and upwelling by ['F Abrantes', 'T Rodrigues', 'B Montanari', 'AHL Voelker', 'C Santos', 'L Witt', 'C Lopes']
Publication: PANGAEA by ['F. Abrantes']
- Paleo Table: Eur-CoastofPortugal.Abrantes.2011.paleo1measurement1.csv

   temperature      year
0       15.235   971.190
1       15.329   982.672
2       15.264   991.858
3       15.376  1001.044
4       15.400  1010.230

temperature {'@id': 'http://linked.earth/lipd/Eur-CoastofPortugal.Abrantes.2011.paleo1measurement1.Eur_010.temperature', 'calibration': [{'@id': 'http://linked.earth/lipd/Eur-CoastofPortugal.Abrantes.2011.paleo1measurement1.Eur_010.temperature.Calibration', 'uncertainty': 'Eur-CoastofPortugal.Abrantes.2011.paleo1measurement1.Eur_010.temperature.Calibration.Uncertainty'}], 'interpretation': [{'@id': 'http://linked.earth/lipd/Eur-CoastofPortugal.Abrantes.2011.paleo1measurement1.Eur_010.temperature.Interpretation1', 'basis': 'correlation with local meteorological correlation', 'direction': 'positive', 'scope': 'climate', 'seasonality': 'Summer', 'variable': 'temperature', 'variableDetail': 'sea@surface'}], 'archiveType': 'Marine sediment', 'number': 1, 'description': 'inferred sea-surface temperature', 'hasMaxValue': 15.952, 'hasMeanValue': 14.9005, 'hasMedianValue': 14.886, 'hasMinValue': 14.194, 'variableName': 'temperature', 'notes': 'SST determinations based on the alkenone index UK37 indicate annual upwelling in tensity as the determinant factor for SST variability confirming the Tagus results (Abrantes et al. 2009)', 'inCompilationBeta': {'@id': 'http://linked.earth/lipd/Pages2kTemperature.66deb38535910', 'compilationName': 'Pages2kTemperature', 'compilationVersion': '2_1_1'}, 'proxy': 'alkenone', 'resolution': {'@id': 'http://linked.earth/lipd/Eur-CoastofPortugal.Abrantes.2011.paleo1measurement1.Eur_010.temperature.Resolution', 'hasMaxValue': 22.965, 'hasMeanValue': 8.8863, 'hasMedianValue': 9.186, 'units': 'yr AD'}, 'hasStandardVariable': 'temperature', 'units': 'degC', 'TSid': 'Eur_010', 'variableType': 'inferred', 'useInGlobalTemperatureAnalysis': True, 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Eur-CoastofPortugal.Abrantes.2011.txt', 'pages2kID': 'Ocn_133', 'precededBy': 'Eur_010', 'measurementTableName': 'measurementTable1', 'measurementTableMD5': '121c7c34a703a81163acba4ab888fb98', 'paleoDataTableName': 'measTable', 'qCCertification': 'JPW', 'inferredVariableType': 'Temperature'}
year {'@id': 'http://linked.earth/lipd/Eur-CoastofPortugal.Abrantes.2011.paleo1measurement1.PYTNSKF0DVD.year', 'archiveType': 'Marine sediment', 'number': 2, 'description': 'Year AD', 'hasMaxValue': 1993.111, 'hasMeanValue': 1530.0393, 'hasMedianValue': 1561.378, 'hasMinValue': 971.19, 'variableName': 'year', 'resolution': {'@id': 'http://linked.earth/lipd/Eur-CoastofPortugal.Abrantes.2011.paleo1measurement1.PYTNSKF0DVD.year.Resolution', 'hasMaxValue': 22.965, 'hasMeanValue': 8.8863, 'hasMedianValue': 9.186, 'units': 'yr AD'}, 'hasStandardVariable': 'year', 'units': 'yr AD', 'TSid': 'PYTNSKF0DVD', 'variableType': 'inferred', 'measurementTableName': 'measurementTable1', 'paleoDataTableName': 'measTable', 'inferredVariableType': 'Year', 'measurementTableMD5': '121c7c34a703a81163acba4ab888fb98', 'dataType': 'float', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Eur-CoastofPortugal.Abrantes.2011.txt'}
Missing Value: NaN
- temperature [degC]
- year [yr AD]


Eur-SpanishPyrenees.Dorado-Linan.2012
=========================
Publication: Estimating 750 years of temperature variations and uncertainties in the Pyrenees by tree-ring reconstructions and climate simulations by ['M. Brunet', 'F. González-Rouco', 'I. Heinrich', 'J. P. Montávez', 'I. Dorado Liñán', 'J. J. Gómez-Navarro', 'U. Büntgen', 'E. Zorita', 'E. Gutiérrez', 'G. Helle']
Publication: World Data Center for Paleoclimatology by ['I. Dorado-Linan']
- Paleo Table: Eur-SpanishPyrenees.Dorado-Linan.2012.paleo1measurement1.csv

   year  ringWidth
0  1260     -1.612
1  1261     -0.703
2  1262     -0.360
3  1263     -0.767
4  1264     -0.601

year {'@id': 'http://linked.earth/lipd/Eur-SpanishPyrenees.Dorado-Linan.2012.paleo1measurement1.PYT2K8MIA3N.year', 'archiveType': 'Wood', 'number': 2, 'description': 'Year AD', 'hasMaxValue': 2005.0, 'hasMeanValue': 1632.5, 'hasMedianValue': 1632.5, 'hasMinValue': 1260.0, 'variableName': 'year', 'resolution': {'@id': 'http://linked.earth/lipd/Eur-SpanishPyrenees.Dorado-Linan.2012.paleo1measurement1.PYT2K8MIA3N.year.Resolution', 'hasMaxValue': 1.0, 'hasMeanValue': 1.0, 'hasMedianValue': 1.0, 'hasMinValue': 1.0, 'units': 'yr AD'}, 'hasStandardVariable': 'year', 'units': 'yr AD', 'TSid': 'PYT2K8MIA3N', 'variableType': 'inferred', 'paleoDataTableName': 'measTable', 'inferredVariableType': 'Year', 'dataType': 'float', 'measurementTableMD5': '7e9437e8b1b34987bb7f2f3b1f0dd3f0', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Eur-SpanishPyrenees.Dorado-Linan.2012.txt', 'measurementTableName': 'measurementTable1'}
ringWidth {'@id': 'http://linked.earth/lipd/Eur-SpanishPyrenees.Dorado-Linan.2012.paleo1measurement1.Eur_020.trsgi', 'interpretation': [{'@id': 'http://linked.earth/lipd/Eur-SpanishPyrenees.Dorado-Linan.2012.paleo1measurement1.Eur_020.trsgi.Interpretation1', 'basis': 'correlation with local meteorological correlation', 'direction': 'positive', 'scope': 'climate', 'seasonality': 'Summer', 'variable': 'temperature', 'variableDetail': 'air@surface'}], 'archiveType': 'Wood', 'number': 1, 'hasMaxValue': 1.278, 'hasMeanValue': -0.2071, 'hasMedianValue': -0.1775, 'hasMinValue': -2.66, 'variableName': 'trsgi', 'notes': 'Regional chronologies based on nested PCs display high correlation coefficients in the two calibration periods: both regression-calibrated (r1900_1952 = 0.81 and r1953_2005 = 0.75 on average) and scaling-calibrated (r1900_1952 = 0.73 and r1953_2005 = 0.80 on average). Similarly REs are also high (well above 0) for the two verifications.', 'inCompilationBeta': {'@id': 'http://linked.earth/lipd/Pages2kTemperature.66deb385437ac', 'compilationName': 'Pages2kTemperature', 'compilationVersion': '2_1_1'}, 'proxy': 'ring width', 'resolution': {'@id': 'http://linked.earth/lipd/Eur-SpanishPyrenees.Dorado-Linan.2012.paleo1measurement1.Eur_020.trsgi.Resolution', 'hasMaxValue': 1.0, 'hasMeanValue': 1.0, 'hasMedianValue': 1.0, 'hasMinValue': 1.0, 'units': 'yr AD'}, 'hasStandardVariable': 'ringWidth', 'TSid': 'Eur_020', 'variableType': 'measured', 'measurementTableMD5': '7e9437e8b1b34987bb7f2f3b1f0dd3f0', 'paleoDataTableName': 'measTable', 'useInGlobalTemperatureAnalysis': True, 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Eur-SpanishPyrenees.Dorado-Linan.2012.txt', 'measurementTableName': 'measurementTable1', 'pages2kID': 'Eur_009', 'proxyObservationType': 'trsgi', 'qCCertification': 'JPW'}
Missing Value: NaN
- year [yr AD]
- trsgi


Eur-FinnishLakelands.Helama.2014
=========================
Publication: World Data Center for Paleoclimatology by ['S. Helama']
Publication: A palaeotemperature record for the Finnish Lakeland based on microdensitometric variations in tree rings by ['Hanna Mäkelä', 'Matti Vartiainen', 'Samuli Helama', 'Jouko Meriläinen', 'Jari Holopainen', 'Taneli Kolström']
- Paleo Table: Eur-FinnishLakelands.Helama.2014.paleo1measurement1.csv

   year  temperature
0  2000       14.603
1  1999       14.643
2  1998       12.074
3  1997       13.898
4  1996       13.671

year {'@id': 'http://linked.earth/lipd/Eur-FinnishLakelands.Helama.2014.paleo1measurement1.PYTUSB62S0A.year', 'archiveType': 'Wood', 'number': 2, 'description': 'Year AD', 'hasMaxValue': 2000.0, 'hasMeanValue': 1380.0, 'hasMedianValue': 1380.0, 'hasMinValue': 760.0, 'variableName': 'year', 'resolution': {'@id': 'http://linked.earth/lipd/Eur-FinnishLakelands.Helama.2014.paleo1measurement1.PYTUSB62S0A.year.Resolution', 'hasMaxValue': 1.0, 'hasMeanValue': 1.0, 'hasMedianValue': 1.0, 'hasMinValue': 1.0, 'units': 'yr AD'}, 'hasStandardVariable': 'year', 'units': 'yr AD', 'TSid': 'PYTUSB62S0A', 'variableType': 'inferred', 'paleoDataTableName': 'measTable', 'dataType': 'float', 'measurementTableName': 'measurementTable1', 'inferredVariableType': 'Year', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Eur-FinnishLakelands.Helama.2014.txt', 'measurementTableMD5': '59aaf55caeb739a42de82831c04da3d3'}
temperature {'@id': 'http://linked.earth/lipd/Eur-FinnishLakelands.Helama.2014.paleo1measurement1.Eur_005.temperature', 'calibration': [{'@id': 'http://linked.earth/lipd/Eur-FinnishLakelands.Helama.2014.paleo1measurement1.Eur_005.temperature.Calibration', 'uncertainty': 'Eur-FinnishLakelands.Helama.2014.paleo1measurement1.Eur_005.temperature.Calibration.Uncertainty'}], 'interpretation': [{'@id': 'http://linked.earth/lipd/Eur-FinnishLakelands.Helama.2014.paleo1measurement1.Eur_005.temperature.Interpretation1', 'basis': 'correlation with local meteorological correlation', 'direction': 'positive', 'scope': 'climate', 'seasonality': 'Summer', 'variable': 'temperature', 'variableDetail': 'air@surface'}], 'archiveType': 'Wood', 'number': 1, 'hasMaxValue': 15.463, 'hasMeanValue': 12.459, 'hasMedianValue': 12.47, 'hasMinValue': 9.408, 'variableName': 'temperature', 'notes': 'Calibrating and verifying the MXD chronologies against the instrumental temperature data showed a promising opportunity to reconstruct warm-season (May through September) temperature variability', 'inCompilationBeta': {'@id': 'http://linked.earth/lipd/Pages2kTemperature.66deb38546cbf', 'compilationName': 'Pages2kTemperature', 'compilationVersion': '2_1_1'}, 'proxy': 'maximum latewood density', 'resolution': {'@id': 'http://linked.earth/lipd/Eur-FinnishLakelands.Helama.2014.paleo1measurement1.Eur_005.temperature.Resolution', 'hasMaxValue': 1.0, 'hasMeanValue': 1.0, 'hasMedianValue': 1.0, 'hasMinValue': 1.0, 'units': 'yr AD'}, 'hasStandardVariable': 'temperature', 'units': 'degC', 'TSid': 'Eur_005', 'variableType': 'inferred', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Eur-FinnishLakelands.Helama.2014.txt', 'precededBy': 'Arc_15', 'measurementTableMD5': '59aaf55caeb739a42de82831c04da3d3', 'pages2kID': 'Eur_013', 'qCCertification': 'JPW', 'useInGlobalTemperatureAnalysis': True, 'inferredVariableType': 'Temperature', 'measurementTableName': 'measurementTable1', 'paleoDataTableName': 'measTable'}
Missing Value: NaN
- year [yr AD]
- temperature [degC]


Eur-NorthernScandinavia.Esper.2012
=========================
Publication: World Data Center for Paleoclimatology by ['J. Esper']
Publication: Orbital forcing of tree-ring data by ['Jürg Luterbacher', 'Rob J. S. Wilson', 'Anne Verstege', 'Mauri Timonen', 'Steffen Holzkämper', 'Sebastian Wagner', 'Jan Esper', 'Eduardo Zorita', 'Nils Fischer', 'Ulf Büntgen', 'David C. Frank', 'Daniel Nievergelt']
- Paleo Table: Eur-NorthernScandinavia.Esper.2012.paleo1measurement1.csv

   year    MXD
0  -138  0.460
1  -137  1.305
2  -136  0.755
3  -135 -0.100
4  -134 -0.457

year {'@id': 'http://linked.earth/lipd/Eur-NorthernScandinavia.Esper.2012.paleo1measurement1.PYTECO66XAD.year', 'archiveType': 'Wood', 'number': 2, 'description': 'Year AD', 'hasMaxValue': 2006.0, 'hasMeanValue': 934.4356, 'hasMedianValue': 934.5, 'hasMinValue': -138.0, 'variableName': 'year', 'resolution': {'@id': 'http://linked.earth/lipd/Eur-NorthernScandinavia.Esper.2012.paleo1measurement1.PYTECO66XAD.year.Resolution', 'hasMaxValue': 2.0, 'hasMeanValue': 1.0005, 'hasMedianValue': 1.0, 'hasMinValue': 1.0, 'units': 'yr AD'}, 'hasStandardVariable': 'year', 'units': 'yr AD', 'TSid': 'PYTECO66XAD', 'variableType': 'inferred', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Eur-NorthernScandinavia.Esper.2012.txt', 'measurementTableName': 'measurementTable1', 'inferredVariableType': 'Year', 'measurementTableMD5': '866c199d9933a1e5ebb28057c960dd22', 'paleoDataTableName': 'measTable', 'dataType': 'float'}
MXD {'@id': 'http://linked.earth/lipd/Eur-NorthernScandinavia.Esper.2012.paleo1measurement1.Eur_014.MXD', 'interpretation': [{'@id': 'http://linked.earth/lipd/Eur-NorthernScandinavia.Esper.2012.paleo1measurement1.Eur_014.MXD.Interpretation1', 'basis': 'correlation with local meteorological correlation', 'direction': 'positive', 'scope': 'climate', 'seasonality': 'Summer', 'variable': 'temperature', 'variableDetail': 'air@surface'}], 'archiveType': 'Wood', 'number': 1, 'hasMaxValue': 2.588, 'hasMeanValue': -0.0602, 'hasMedianValue': -0.049, 'hasMinValue': -3.124, 'variableName': 'MXD', 'notes': 'The final reconstruction (N-scan) was calibrated against regional JJA temperature (r 1876_2006 = 0.77) and spans the 138 bc_ ad 2006 period.', 'inCompilationBeta': {'@id': 'http://linked.earth/lipd/Pages2kTemperature.66deb3854a693', 'compilationName': 'Pages2kTemperature', 'compilationVersion': '2_1_1'}, 'proxy': 'maximum latewood density', 'resolution': {'@id': 'http://linked.earth/lipd/Eur-NorthernScandinavia.Esper.2012.paleo1measurement1.Eur_014.MXD.Resolution', 'hasMaxValue': 2.0, 'hasMeanValue': 1.0005, 'hasMedianValue': 1.0, 'hasMinValue': 1.0, 'units': 'yr AD'}, 'hasStandardVariable': 'MXD', 'TSid': 'Eur_014', 'variableType': 'measured', 'useInGlobalTemperatureAnalysis': True, 'measurementTableMD5': '866c199d9933a1e5ebb28057c960dd22', 'pages2kID': 'Eur_003', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Eur-NorthernScandinavia.Esper.2012.txt', 'measurementTableName': 'measurementTable1', 'paleoDataTableName': 'measTable', 'proxyObservationType': 'MXD', 'qCCertification': 'JPW'}
Missing Value: NaN
- year [yr AD]
- MXD


Eur-Stockholm.Leijonhufvud.2009
=========================
Publication: Five centuries of Stockholm winter/spring temperatures reconstructed from documentary evidence and instrumental observations by ['Rob Wilson', 'Anders Moberg', 'Ulrica Söderlind', 'Dag Retsö', 'Lotta Leijonhufvud', 'Johan Söderberg']
Publication: World Data Center for Paleoclimatology by ['L. Leijonhufvud']
- Paleo Table: Eur-Stockholm.Leijonhufvud.2009.paleo1measurement1.csv

   year  temperature
0  1502      -1.7212
1  1503      -1.6382
2  1504      -0.6422
3  1505       0.1048
4  1506      -0.7252

year {'@id': 'http://linked.earth/lipd/Eur-Stockholm.Leijonhufvud.2009.paleo1measurement1.PYTWVH672OU.year', 'archiveType': 'Documents', 'number': 2, 'description': 'Year AD', 'hasMaxValue': 1892.0, 'hasMeanValue': 1697.0, 'hasMedianValue': 1697.0, 'hasMinValue': 1502.0, 'variableName': 'year', 'resolution': {'@id': 'http://linked.earth/lipd/Eur-Stockholm.Leijonhufvud.2009.paleo1measurement1.PYTWVH672OU.year.Resolution', 'hasMaxValue': 1.0, 'hasMeanValue': 1.0, 'hasMedianValue': 1.0, 'hasMinValue': 1.0, 'units': 'yr AD'}, 'hasStandardVariable': 'year', 'units': 'yr AD', 'TSid': 'PYTWVH672OU', 'variableType': 'inferred', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Eur-Stockholm.Leijonhufvud.2009.txt', 'measurementTableMD5': 'a26e3a157e304c236bf91e17f8f7751b', 'dataType': 'float', 'measurementTableName': 'measurementTable1', 'paleoDataTableName': 'measTable', 'inferredVariableType': 'Year'}
temperature {'@id': 'http://linked.earth/lipd/Eur-Stockholm.Leijonhufvud.2009.paleo1measurement1.Eur_006.temperature', 'calibration': [{'@id': 'http://linked.earth/lipd/Eur-Stockholm.Leijonhufvud.2009.paleo1measurement1.Eur_006.temperature.Calibration', 'uncertainty': 'Eur-Stockholm.Leijonhufvud.2009.paleo1measurement1.Eur_006.temperature.Calibration.Uncertainty'}], 'interpretation': [{'@id': 'http://linked.earth/lipd/Eur-Stockholm.Leijonhufvud.2009.paleo1measurement1.Eur_006.temperature.Interpretation1', 'basis': 'correlation with local meteorological correlation', 'direction': 'positive', 'scope': 'climate', 'seasonality': 'Winter', 'variable': 'temperature', 'variableDetail': 'air@surface'}], 'archiveType': 'Documents', 'number': 1, 'hasMaxValue': 4.9385, 'hasMeanValue': -0.7404, 'hasMedianValue': -0.8524, 'hasMinValue': -6.3995, 'variableName': 'temperature', 'notes': 'By refining dendroclimatological methods the time-series were composited to a mean series and calibrated (1756_1841; r2 = 66%) against Stockholm January_April temperatures.', 'inCompilationBeta': {'@id': 'http://linked.earth/lipd/Pages2kTemperature.66deb3854dc93', 'compilationName': 'Pages2kTemperature', 'compilationVersion': '2_1_1'}, 'proxy': 'historical', 'resolution': {'@id': 'http://linked.earth/lipd/Eur-Stockholm.Leijonhufvud.2009.paleo1measurement1.Eur_006.temperature.Resolution', 'hasMaxValue': 1.0, 'hasMeanValue': 1.0, 'hasMedianValue': 1.0, 'hasMinValue': 1.0, 'units': 'yr AD'}, 'hasStandardVariable': 'temperature', 'units': 'degC', 'TSid': 'Eur_006', 'variableType': 'inferred', 'wDSPaleoUrl': 'https://www1.ncdc.noaa.gov/pub/data/paleo/pages2k/pages2k-temperature-v2-2017/data-version-2.0.0/Eur-Stockholm.Leijonhufvud.2009.txt', 'qCCertification': 'JPW', 'measurementTableMD5': 'a26e3a157e304c236bf91e17f8f7751b', 'measurementTableName': 'measurementTable1', 'inferredVariableType': 'Temperature', 'useInGlobalTemperatureAnalysis': True, 'pages2kID': 'Eur_019', 'paleoDataTableName': 'measTable'}
Missing Value: NaN
- year [yr AD]
- temperature [degC]

## Editing an existing LiPD file

In [2]:
# Dataset is the Main OOP Class
from pylipd.classes.dataset import Dataset

# LiPD is the LiPD parser/writer
from pylipd.classes.datatable import DataTable
from pylipd.lipd import LiPD

# Load LiPD files as usual.
# - This loads the LiPD data into the internal RDF graph
path = '../data/ODP846.Lawrence.2006.lpd'
D = LiPD()
D.load(path)

# Convert the LiPD datasets to the PyLiPD OOP "Dataset" class. 
# - This allows to modify the datasets via OOP calls in memory
# - To write the LiPD back, we have to call the save function
datasets = D.get_datasets()

ds = datasets[0]
pdata = ds.getPaleoData()[0]

# ********************************************
# We will add a table to the paleoData here
# ********************************************
attrs = {
    "site": {
        'number': 1, 
        'variableName': 'site/hole', 
        'hasStandardVariable': 'site', 
        'units': 'unitless', 
        'TSid': 'PYTJ3PSH0LT', 
        'variableType': 'measured', 
        'takenAtDepth': 'depth'
    },
    "ukprime37": {
        'number': 2,
        'interpretation': [
            {
                'rank': 1.0, 
                'scope': 'Climate', 
                'variable': 'temperature', 
                'variableDetail': 'sea surface', 
                'direction': 'positive'
            }
        ], 
        'variableName': 'ukprime37', 
        'resolution': {
            'hasMaxValue': 10.856999999999971, 
            'hasMeanValue': 2.3355875057418465, 
            'hasMedianValue': 2.211999999999989, 
            'hasMinValue': 0.06999999999993634
        }, 
        'units': 'unitless', 
        'TSid': 'PYTM9N6HCQM', 
        'variableType': 'measured', 
        'takenAtDepth': 'depth', 
        'proxyObservationType': 'Uk37Prime'
    },
    "age": {
        'interpretation': [
            {
                'rank': 1.0, 
                'scope': 'Age', 
                'variableDetail': 'calendar', 
                'direction': 'positive'
            }
        ], 
        'number': 3, 
        'variableName': 'age', 
        'hasStandardVariable': 'age', 
        'TSid': 'PYTXJB98403', 
        'variableType': 'inferred', 
        'takenAtDepth': 'depth', 
        'inferredVariableType': 'Age'
    },
    "depth": {
        'number': 4, 
        'variableName': 'depth', 
        'notes': 'depth rmcd', 
        'resolution': {
            'hasMaxValue': 10.856999999999971, 
            'hasMeanValue': 2.3355875057418465, 
            'hasMedianValue': 2.211999999999989, 
            'hasMinValue': 0.06999999999993634
        }, 
        'hasStandardVariable': 'depth', 
        'units': 'm', 
        'TSid': 'PYTKRFVW61B', 
        'variableType': 'measured'
    }
}

# Create a random dataframe
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(100, 4), columns=attrs.keys())
df.attrs = attrs
display(df.head())

newtable = DataTable()
newtable.setFileName("paleo0measurement2.csv")
newtable.setMissingValue("NaN")
newtable.setDataFrame(df)

pdata.addMeasurementTable(newtable)

# Create a lipd from the Dataset ds
savelipd = LiPD()
savelipd.load_datasets([ds])
savelipd.create_lipd(ds.getName(), "./ODP846.Lawrence.2006.updated.lpd")
pass

Loading 1 LiPD files

100%|██████████| 1/1 [00:00<00:00,  1.73it/s]

Loaded..

       site  ukprime37       age     depth
0 -0.909061  -0.860013  0.500737  1.800685
1  0.236617   0.564153 -0.442693  0.713587
2 -1.355983  -0.203197  0.260957 -1.764060
3  0.465364   0.475315 -0.555199 -1.188082
4  0.182585   2.142508 -0.695586  0.322117

In [3]:
# Try to load the New LiPD File, and check if everything is ok
D = LiPD()
D.load("./ODP846.Lawrence.2006.updated.lpd")

Loading 1 LiPD files

100%|██████████| 1/1 [00:00<00:00,  1.80it/s]

Loaded..

In [4]:
# Try to load the New LiPD File, and check if everything is ok
D = LiPD()
D.load("./ODP846.Lawrence.2006.updated.lpd")
datasets = D.get_datasets()

# Browse the dataset as usual
for ds in datasets:
    print("\n")
    print(ds.getName())
    print("=========================")
    for pdata in ds.getPaleoData():
        for table in pdata.getMeasurementTables():
            print(f"- Paleo Table: {table.getFileName()}")
            
            # Can get the dataframe for the whole table
            df = table.getDataFrame(use_standard_names=True)
            display(df.head())

            # The returned dataframe also contains the attributes for the variables
            for varname in df.attrs:
                vardata = df.attrs[varname]
                print(varname, vardata)

            # Can also get the variables one by one and make calls to their class functions
            print(f"Missing Value: {table.getMissingValue()}")
            for var in table.getVariables():
                if var.getUnits():
                    print(f"- {var.getName()} [{var.getUnits().getLabel()}]")
                else:
                    print(f"- {var.getName()}")

Loading 1 LiPD files

100%|██████████| 1/1 [00:00<00:00,  1.81it/s]

Loaded..


ODP846.Lawrence.2006
=========================
- Paleo Table: paleo0measurement1.csv

,u. peregrina d13c,c. wuellerstorfi d13c,c. wuellerstorfi d18o,u. peregrina d18o,depth comp,depth cr,depth,event,sampleID
0,NaN,3.38,0.12,0.14,12.0,0.12,0.12,138-846B,138-846B-1H-1
1,NaN,3.46,0.23,0.01,23.0,0.23,0.23,138-846B,138-846B-1H-1
2,NaN,3.65,0.33,-0.10,33.0,0.33,0.33,138-846B,138-846B-1H-1
3,NaN,3.88,0.33,-0.06,33.0,0.33,0.33,138-846B,138-846B-1H-1
4,NaN,4.14,0.43,-0.17,43.0,0.43,0.43,138-846B,138-846B-1H-1

u. peregrina d13c {'@id': 'http://linked.earth/lipd/paleo0measurement1.PYTTUPVG4K3.u._peregrina_d13c', 'number': 9, 'hasMaxValue': 28.388, 'hasMeanValue': 24.379435830618892, 'hasMedianValue': 26.018, 'hasMinValue': -1.0, 'variableName': 'u. peregrina d13c', 'physicalSample': 'http://linked.earth/lipd/Unknown.66decdd89d57b', 'resolution': {'@id': 'http://linked.earth/lipd/paleo0measurement1.PYTTUPVG4K3.u._peregrina_d13c.Resolution'}, 'TSid': 'PYTTUPVG4K3', 'variableType': 'measured', 'sensorSpecies': 'peregrina', 'sensorGenus': 'Uvigerina', 'takenAtDepth': 'depth', 'proxyObservationType': 'd13C'}
c. wuellerstorfi d13c {'@id': 'http://linked.earth/lipd/paleo0measurement1.PYT19MC8WE2.c._wuellerstorfi_d13c', 'number': 7, 'hasMaxValue': 78.92, 'hasMeanValue': 6.293517145505097, 'hasMedianValue': 4.26, 'hasMinValue': -1.06, 'variableName': 'c. wuellerstorfi d13c', 'physicalSample': 'http://linked.earth/lipd/Unknown.66decdd89d305', 'resolution': {'@id': 'http://linked.earth/lipd/paleo0measurement1.PYT19MC8WE2.c._wuellerstorfi_d13c.Resolution'}, 'TSid': 'PYT19MC8WE2', 'variableType': 'measured', 'sensorGenus': 'Cibicidoides', 'sensorSpecies': 'wuellerstorfi', 'takenAtDepth': 'depth', 'proxyObservationType': 'd13C'}
c. wuellerstorfi d18o {'@id': 'http://linked.earth/lipd/paleo0measurement1.PYT3ZMI0BXW.c._wuellerstorfi_d18o', 'number': 6, 'hasMaxValue': 27.7, 'hasMeanValue': 18.295537534754406, 'hasMedianValue': 24.6, 'hasMinValue': 2.92, 'variableName': 'c. wuellerstorfi d18o', 'physicalSample': 'http://linked.earth/lipd/Unknown.66decdd89d1b8', 'resolution': {'@id': 'http://linked.earth/lipd/paleo0measurement1.PYT3ZMI0BXW.c._wuellerstorfi_d18o.Resolution'}, 'TSid': 'PYT3ZMI0BXW', 'variableType': 'measured', 'sensorSpecies': 'wuellerstorfi', 'proxyObservationType': 'd18O', 'sensorGenus': 'Cibicidoides', 'takenAtDepth': 'depth'}
u. peregrina d18o {'@id': 'http://linked.earth/lipd/paleo0measurement1.PYTYDOYFVYD.u._peregrina_d18o', 'number': 8, 'hasMaxValue': 4.96, 'hasMeanValue': 1.096672312703583, 'hasMedianValue': 0.913, 'hasMinValue': 0.753, 'variableName': 'u. peregrina d18o', 'physicalSample': 'http://linked.earth/lipd/Unknown.66decdd89d44d', 'resolution': {'@id': 'http://linked.earth/lipd/paleo0measurement1.PYTYDOYFVYD.u._peregrina_d18o.Resolution'}, 'TSid': 'PYTYDOYFVYD', 'variableType': 'measured', 'takenAtDepth': 'depth', 'sensorGenus': 'Uvigerina', 'sensorSpecies': 'peregrina', 'proxyObservationType': 'd18O'}
depth comp {'@id': 'http://linked.earth/lipd/paleo0measurement1.PYTPQ0FJO1S.depth_comp', 'number': 4, 'hasMaxValue': 196.93, 'hasMeanValue': 97.84506844281121, 'hasMedianValue': 96.359, 'hasMinValue': 0.12, 'variableName': 'depth comp', 'physicalSample': 'http://linked.earth/lipd/Unknown.66decdd89cee6', 'resolution': {'@id': 'http://linked.earth/lipd/paleo0measurement1.PYTPQ0FJO1S.depth_comp.Resolution'}, 'TSid': 'PYTPQ0FJO1S', 'variableType': 'measured', 'takenAtDepth': 'depth'}
depth cr {'@id': 'http://linked.earth/lipd/paleo0measurement1.PYT68HYMYHH.depth_cr', 'number': 5, 'hasMaxValue': 5089.802, 'hasMeanValue': 2234.3875783187873, 'hasMedianValue': 2507.177, 'hasMinValue': 0.12, 'variableName': 'depth cr', 'physicalSample': 'http://linked.earth/lipd/Unknown.66decdd89d077', 'resolution': {'@id': 'http://linked.earth/lipd/paleo0measurement1.PYT68HYMYHH.depth_cr.Resolution'}, 'TSid': 'PYT68HYMYHH', 'variableType': 'measured', 'takenAtDepth': 'depth'}
depth {'@id': 'http://linked.earth/lipd/paleo0measurement1.PYTS96EE0CB.depth', 'number': 2, 'hasMaxValue': 61.17, 'hasMeanValue': 18.667220946256318, 'hasMedianValue': 18.0, 'hasMinValue': 0.12, 'variableName': 'depth', 'physicalSample': 'http://linked.earth/lipd/Unknown.66decdd89cd11', 'hasStandardVariable': 'depth', 'units': 'm', 'TSid': 'PYTS96EE0CB', 'variableType': 'measured'}
event {'@id': 'http://linked.earth/lipd/paleo0measurement1.PYTE5EC1JBW.event', 'number': 1, 'hasMaxValue': 846.0, 'hasMeanValue': 606.9646302250804, 'hasMedianValue': 846.0, 'hasMinValue': 138.0, 'variableName': 'event', 'physicalSample': 'http://linked.earth/lipd/Unknown.66decdd89cc7a', 'hasStandardVariable': 'event', 'units': 'unitless', 'TSid': 'PYTE5EC1JBW', 'variableType': 'measured', 'takenAtDepth': 'depth'}
sampleID {'@id': 'http://linked.earth/lipd/paleo0measurement1.PYTJZ4GLRYP.sampleID', 'number': 3, 'hasMaxValue': 145.0, 'hasMeanValue': 94.06663602941177, 'hasMedianValue': 138.0, 'hasMinValue': 3.0, 'variableName': 'sampleID', 'physicalSample': 'http://linked.earth/lipd/Unknown.66decdd89cdaa', 'hasStandardVariable': 'sampleID', 'units': 'unitless', 'TSid': 'PYTJZ4GLRYP', 'variableType': 'measured', 'takenAtDepth': 'depth'}
Missing Value: nan
- u. peregrina d13c
- c. wuellerstorfi d13c
- c. wuellerstorfi d18o
- u. peregrina d18o
- depth comp
- depth cr
- depth [m]
- event [unitless]
- sampleID [unitless]
- Paleo Table: paleo0measurement2.csv

      depth      site       age  ukprime37
0  1.800685 -0.909061  0.500737  -0.860013
1  0.713587  0.236617 -0.442693   0.564153
2 -1.764060 -1.355983  0.260957  -0.203197
3 -1.188082  0.465364 -0.555199   0.475315
4  0.322117  0.182585 -0.695586   2.142508

depth {'@id': 'http://linked.earth/lipd/paleo0measurement2.PYTKRFVW61B.depth', 'number': 4, 'variableName': 'depth', 'notes': 'depth rmcd', 'resolution': {'@id': 'http://linked.earth/lipd/paleo0measurement2.PYTKRFVW61B.depth.Resolution', 'hasMaxValue': 10.856999999999971, 'hasMeanValue': 2.3355875057418465, 'hasMedianValue': 2.211999999999989, 'hasMinValue': 0.06999999999993634}, 'hasStandardVariable': 'depth', 'units': 'm', 'TSid': 'PYTKRFVW61B', 'variableType': 'measured'}
site {'@id': 'http://linked.earth/lipd/paleo0measurement2.PYTJ3PSH0LT.site', 'number': 1, 'variableName': 'site', 'hasStandardVariable': 'site', 'units': 'unitless', 'TSid': 'PYTJ3PSH0LT', 'variableType': 'measured', 'takenAtDepth': 'depth'}
age {'@id': 'http://linked.earth/lipd/paleo0measurement2.PYTXJB98403.age', 'interpretation': [{'@id': 'http://linked.earth/lipd/paleo0measurement2.PYTXJB98403.age.Interpretation1', 'direction': 'positive', 'scope': 'Age', 'variableDetail': 'calendar'}], 'number': 3, 'variableName': 'age', 'hasStandardVariable': 'age', 'TSid': 'PYTXJB98403', 'variableType': 'inferred', 'takenAtDepth': 'depth', 'inferredVariableType': 'Age'}
ukprime37 {'@id': 'http://linked.earth/lipd/paleo0measurement2.PYTM9N6HCQM.ukprime37', 'interpretation': [{'@id': 'http://linked.earth/lipd/paleo0measurement2.PYTM9N6HCQM.ukprime37.Interpretation1', 'direction': 'positive', 'scope': 'Climate', 'variable': 'temperature', 'variableDetail': 'sea surface'}], 'number': 2, 'variableName': 'ukprime37', 'resolution': {'@id': 'http://linked.earth/lipd/paleo0measurement2.PYTM9N6HCQM.ukprime37.Resolution', 'hasMaxValue': 10.856999999999971, 'hasMeanValue': 2.3355875057418465, 'hasMedianValue': 2.211999999999989, 'hasMinValue': 0.06999999999993634}, 'units': 'unitless', 'TSid': 'PYTM9N6HCQM', 'variableType': 'measured', 'proxyObservationType': 'Uk37Prime', 'takenAtDepth': 'depth'}
Missing Value: NaN
- depth [m]
- site [unitless]
- age
- ukprime37 [unitless]
- Paleo Table: paleo0measurement0.csv

,c37 total,section,age,temp muller,deleteMe,depth,site,temp prahl,ukprime37
0,2.37,1H-1,5.228,23.545,15-16,0.16,846B,23.0,0.821
1,2.10,1H-1,8.947,23.648,25-26,0.26,846B,23.1,0.824
2,1.87,1H-1,11.966,23.752,35-36,0.36,846B,23.2,0.828
3,2.74,1H-1,14.427,22.515,45-46,0.46,846B,22.0,0.787
4,3.75,1H-1,16.502,22.206,55-56,0.56,846B,21.7,0.777

c37 total {'@id': 'http://linked.earth/lipd/paleo0measurement0.PYT10H23U2E.c37_total', 'number': 7, 'hasMaxValue': 78.92, 'hasMeanValue': 9.900032139577593, 'hasMedianValue': 7.075, 'hasMinValue': 1.095, 'variableName': 'c37 total', 'physicalSample': 'http://linked.earth/lipd/Unknown.66decdd89dd80', 'resolution': {'@id': 'http://linked.earth/lipd/paleo0measurement0.PYT10H23U2E.c37_total.Resolution', 'hasMaxValue': 10.856999999999971, 'hasMeanValue': 2.3355875057418465, 'hasMedianValue': 2.211999999999989, 'hasMinValue': 0.06999999999993634}, 'TSid': 'PYT10H23U2E', 'variableType': 'measured', 'proxyObservationType': 'Alkenone', 'takenAtDepth': 'depth'}
section {'@id': 'http://linked.earth/lipd/paleo0measurement0.PYT8BDSRW3H.section', 'number': 2, 'hasMaxValue': 19.0, 'hasMeanValue': 9.46694214876033, 'hasMedianValue': 18.0, 'hasMinValue': 1.0, 'variableName': 'section', 'physicalSample': 'http://linked.earth/lipd/Unknown.66decdd89d6b0', 'hasStandardVariable': 'section', 'units': 'unitless', 'TSid': 'PYT8BDSRW3H', 'variableType': 'measured', 'takenAtDepth': 'depth'}
age {'@id': 'http://linked.earth/lipd/paleo0measurement0.PYTXJB98403.age', 'interpretation': [{'@id': 'http://linked.earth/lipd/paleo0measurement0.PYTXJB98403.age.Interpretation1', 'scope': 'Age', 'variableDetail': 'calendar', 'interpdirection': 'positive'}], 'number': 5, 'hasMaxValue': 5089.802, 'hasMeanValue': 2533.4160550964184, 'hasMedianValue': 2507.067, 'hasMinValue': 5.228, 'variableName': 'age', 'resolution': {'@id': 'http://linked.earth/lipd/paleo0measurement0.PYTXJB98403.age.Resolution'}, 'hasStandardVariable': 'age', 'TSid': 'PYTXJB98403', 'variableType': 'inferred', 'inferredVariableType': 'Age', 'takenAtDepth': 'depth'}
temp muller {'@id': 'http://linked.earth/lipd/paleo0measurement0.PYTGO6NV72Y.temp_muller', 'interpretation': [{'@id': 'http://linked.earth/lipd/paleo0measurement0.PYTGO6NV72Y.temp_muller.Interpretation1', 'scope': 'Climate', 'variable': 'temperature', 'variableDetail': 'sea surface', 'interpdirection': 'positive'}], 'number': 9, 'hasMaxValue': 28.388, 'hasMeanValue': 25.105362258953168, 'hasMedianValue': 25.297, 'hasMinValue': 20.558, 'variableName': 'temp muller', 'resolution': {'@id': 'http://linked.earth/lipd/paleo0measurement0.PYTGO6NV72Y.temp_muller.Resolution', 'hasMaxValue': 10.856999999999971, 'hasMeanValue': 2.3355875057418465, 'hasMedianValue': 2.211999999999989, 'hasMinValue': 0.06999999999993634}, 'TSid': 'PYTGO6NV72Y', 'variableType': 'inferred', 'takenAtDepth': 'depth', 'inferredVariableType': 'Sea Surface Temperature'}
deleteMe {'@id': 'http://linked.earth/lipd/paleo0measurement0.PYT2ZB6MLZ9.deleteMe', 'number': 3, 'hasMaxValue': 150.0, 'hasMeanValue': 72.7043035631652, 'hasMedianValue': 3.0, 'hasMinValue': 3.0, 'variableName': 'deleteMe', 'physicalSample': 'http://linked.earth/lipd/Unknown.66decdd89d74e', 'hasStandardVariable': 'deleteMe', 'units': 'cm', 'TSid': 'PYT2ZB6MLZ9', 'variableType': 'measured', 'takenAtDepth': 'depth'}
depth {'@id': 'http://linked.earth/lipd/paleo0measurement0.PYTKRFVW61B.depth', 'number': 4, 'hasMaxValue': 196.93, 'hasMeanValue': 97.99932323232323, 'hasMedianValue': 96.3545, 'hasMinValue': 0.16, 'variableName': 'depth', 'notes': 'depth rmcd', 'physicalSample': 'http://linked.earth/lipd/Unknown.66decdd89d8e9', 'resolution': {'@id': 'http://linked.earth/lipd/paleo0measurement0.PYTKRFVW61B.depth.Resolution', 'hasMaxValue': 10.856999999999971, 'hasMeanValue': 2.3355875057418465, 'hasMedianValue': 2.211999999999989, 'hasMinValue': 0.06999999999993634}, 'hasStandardVariable': 'depth', 'units': 'm', 'TSid': 'PYTKRFVW61B', 'variableType': 'measured'}
site {'@id': 'http://linked.earth/lipd/paleo0measurement0.PYTJ3PSH0LT.site', 'number': 1, 'hasMaxValue': 846.0, 'hasMeanValue': 846.0, 'hasMedianValue': 846.0, 'hasMinValue': 846.0, 'variableName': 'site', 'physicalSample': 'http://linked.earth/lipd/Unknown.66decdd89d620', 'hasStandardVariable': 'site', 'units': 'unitless', 'TSid': 'PYTJ3PSH0LT', 'variableType': 'measured', 'takenAtDepth': 'depth'}
temp prahl {'@id': 'http://linked.earth/lipd/paleo0measurement0.PYT95DVDUU3.temp_prahl', 'calibration': [{'@id': 'http://linked.earth/lipd/paleo0measurement0.PYT95DVDUU3.temp_prahl.Calibration', 'equation': 'UK37 = 0.034T + 0.039', 'reference': 'Publication.10.1016/0016-7037(88)90132-9'}], 'interpretation': [{'@id': 'http://linked.earth/lipd/paleo0measurement0.PYT95DVDUU3.temp_prahl.Interpretation1', 'scope': 'Climate', 'variable': 'temperature', 'variableDetail': 'sea surface', 'interpdirection': 'positive'}], 'number': 6, 'hasMaxValue': 27.7, 'hasMeanValue': 24.514049586776864, 'hasMedianValue': 24.7, 'hasMinValue': 20.1, 'variableName': 'temp prahl', 'resolution': {'@id': 'http://linked.earth/lipd/paleo0measurement0.PYT95DVDUU3.temp_prahl.Resolution', 'hasMaxValue': 10.856999999999971, 'hasMeanValue': 2.3355875057418465, 'hasMedianValue': 2.211999999999989, 'hasMinValue': 0.06999999999993634}, 'TSid': 'PYT95DVDUU3', 'variableType': 'inferred', 'inferredVariableType': 'Sea Surface Temperature', 'takenAtDepth': 'depth'}
ukprime37 {'@id': 'http://linked.earth/lipd/paleo0measurement0.PYTM9N6HCQM.ukprime37', 'interpretation': [{'@id': 'http://linked.earth/lipd/paleo0measurement0.PYTM9N6HCQM.ukprime37.Interpretation1', 'scope': 'Climate', 'variable': 'temperature', 'variableDetail': 'sea surface', 'interpdirection': 'positive'}], 'number': 8, 'hasMaxValue': 0.981, 'hasMeanValue': 0.872473829201102, 'hasMedianValue': 0.879, 'hasMinValue': 0.722, 'variableName': 'ukprime37', 'physicalSample': 'http://linked.earth/lipd/Unknown.66decdd89ded8', 'resolution': {'@id': 'http://linked.earth/lipd/paleo0measurement0.PYTM9N6HCQM.ukprime37.Resolution', 'hasMaxValue': 10.856999999999971, 'hasMeanValue': 2.3355875057418465, 'hasMedianValue': 2.211999999999989, 'hasMinValue': 0.06999999999993634}, 'units': 'unitless', 'TSid': 'PYTM9N6HCQM', 'variableType': 'measured', 'takenAtDepth': 'depth', 'proxyObservationType': 'Uk37Prime'}
Missing Value: nan
- c37 total
- section [unitless]
- age
- temp muller
- deleteMe [cm]
- depth [m]
- site [unitless]
- temp prahl
- ukprime37 [unitless]

## Creating a new LiPD file